### ISSUE TITLE
pipeline 报错

### ISSUE THREAD

**Issue by lawindman666** [alibaba-damo-academy/FunASR#1019]
# fmt: on
 平台:WINDOWS
 python:3.9
 modelscope-1.9.2
 funasr-0.8.0

    model_name = "damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
    inference_pipeline = pipeline(
        task=Tasks.auto_speech_recognition,
        model=model_name)

     出现下面的错误
 2023-10-18 19:34:05,398 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2023-10-18 19:34:05,400 - modelscope - INFO - Loading ast index from C:\Users\PC\.cache\modelscope\ast_indexer
2023-10-18 19:34:05,441 - modelscope - INFO - Loading done! Current index file version is 1.9.2, with md5 4a81b34c08f446cc0a1d96cb22a8ec2f and a total number of 941 components indexed
batch_size_token:6000
cpu_count:20
2023-10-18 19:34:06,432 - modelscope - INFO - Model revision not specified, use revision: v1.2.4
2023-10-18 19:34:06,720 - modelscope - INFO - initiate model from C:\Users\PC\.cache\modelscope\hub\damo\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2023-10-18 19:34:06,720 - modelscope - INFO - initiate model from location C:\Users\PC\.cache\modelscope\hub\damo\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2023-10-18 19:34:06,722 - modelscope - INFO - initialize model from C:\Users\PC\.cache\modelscope\hub\damo\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2023-10-18 19:34:06,727 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-18 19:34:06,727 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-18 19:34:06,728 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\PC\\.cache\\modelscope\\hub\\damo\\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch'}. trying to build by task and model information.
2023-10-18 19:34:06,728 - modelscope - WARNING - No preprocessor key ('generic-asr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-10-18 19:34:07,173 - modelscope - INFO - Model revision not specified, use revision: v1.2.0
2023-10-18 19:34:07,704 - modelscope - INFO - loading vad model from C:\Users\PC\.cache\modelscope\hub\damo\speech_fsmn_vad_zh-cn-16k-common-pytorch ...
2023-10-18 19:34:08,050 - modelscope - INFO - Model revision not specified, use revision: v1.1.7
2023-10-18 19:34:08,401 - modelscope - INFO - loading punctuation model from C:\Users\PC\.cache\modelscope\hub\damo\punc_ct-transformer_zh-cn-common-vocab272727-pytorch ...
Traceback (most recent call last):
  File "D:\conda\envs\funasr\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "D:\conda\envs\funasr\lib\site-packages\modelscope\pipelines\audio\asr_inference_pipeline.py", line 123, in __init__
    from funasr.bin import asr_inference_launch
  File "d:\asr\funasr\funasr-main\funasr\bin\asr_inference_launch.py", line 26, in <module>
    from funasr.bin.asr_infer import Speech2Text
  File "d:\asr\funasr\funasr-main\funasr\bin\asr_infer.py", line 41, in <module>
    from funasr.utils.whisper_utils.decoding import DecodingOptions, detect_language, decode
  File "d:\asr\funasr\funasr-main\funasr\utils\whisper_utils\decoding.py", line 11, in <module>
    from funasr.utils.whisper_utils.tokenizer import Tokenizer, get_tokenizer
  File "d:\asr\funasr\funasr-main\funasr\utils\whisper_utils\tokenizer.py", line 8, in <module>
    from transformers import GPT2TokenizerFast
ModuleNotFoundError: No module named 'transformers'

**Comment by lawindman666** [comment]
看错信息了，安装transformers就好了，不好意思~
