### ISSUE TITLE
result目录下asr_inference.1、train.log报错

### ISSUE THREAD

**Issue by CreepJoye** [alibaba-damo-academy/FunASR#1032]
OS: Ubuntu 18.04.6

Python/C++ Version：python3.8

Package Version：funasr==0.7.8 modelscope==1.9.2 torch==2.0.0  torchaudio==2.0.1+cu118

Model：

Command：`bash run.sh --CUDA_VISIBLE_DEVICES "0,1" --gpu_num 2`

Details：
1.在/home/lqb/project/FunASR/**results/exp/baseline_train_asr_paraformer_conformer_12e_6d_2048_256_zh_char_exp1/decode_asr_transformer_noctc_1best/valid.acc.ave_10best.pb/dev/logdir/asr_inference.1.log**这个目录下，
报错：
```python
Traceback (most recent call last):
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/site-packages/funasr-0.7.8-py3.8.egg/funasr/bin/asr_inference_launch.py", line 1969, in <module>
    main()
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/site-packages/funasr-0.7.8-py3.8.egg/funasr/bin/asr_inference_launch.py", line 1964, in main
    inference_pipeline = inference_launch(**kwargs)
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/site-packages/funasr-0.7.8-py3.8.egg/funasr/bin/asr_inference_launch.py", line 1682, in inference_launch
    return inference_paraformer(**kwargs)
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/site-packages/funasr-0.7.8-py3.8.egg/funasr/bin/asr_inference_launch.py", line 297, in inference_paraformer
    speech2text = Speech2TextParaformer(**speech2text_kwargs)
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/site-packages/funasr-0.7.8-py3.8.egg/funasr/bin/asr_infer.py", line 290, in __init__
    asr_model, asr_train_args = build_model_from_file(
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/site-packages/funasr-0.7.8-py3.8.egg/funasr/build_utils/build_model_from_file.py", line 41, in build_model_from_file
    with config_file.open("r", encoding="utf-8") as f:
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/lqb/miniconda3/envs/funasr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
**FileNotFoundError: [Errno 2] No such file or directory: '/home/lqb/project/FunASR/results/exp/baseline_train_asr_paraformer_conformer_12e_6d_2048_256_zh_char_exp1/config.yaml'**
```
2.
在/home/lqb/project/FunASR/**results/exp/baseline_train_asr_paraformer_conformer_12e_6d_2048_256_zh_char_exp1/log/train.log.0**这个目录下，报错：**/usr/bin/env: "python3\r": 没有那个文件或目录**

Error log：
```python
stage 0: Data preparation
Preparing /home/lqb/project/FunASR/feats/data/local/train transcriptions
Preparing /home/lqb/project/FunASR/feats/data/local/dev transcriptions
Preparing /home/lqb/project/FunASR/feats/data/local/test transcriptions
local/aishell_data_prep.sh: AISHELL data preparation succeeded
stage 1: Feature and CMVN Generation
/home/lqb/project/FunASR/egs/aishell/transformer/utils/compute_cmvn.sh --fbankdir /home/lqb/project/FunASR/feats/data/train --cmd /home/lqb/project/FunASR/egs/aishell/transformer/utils/run.pl --nj 64 --feats_dim 80 --config_file conf/train_asr_paraformer_conformer_12e_6d_2048_256.yaml --scale 1.0
/home/lqb/project/FunASR/egs/aishell/transformer/utils/compute_cmvn.sh: Succeeded compute global cmvn
dictionary: /home/lqb/project/FunASR/feats/data/zh_token_list/char/tokens.txt
stage 2: Dictionary Preparation
make a dictionary
stage 3: LM Training
stage 4: ASR Training
run.sh: init method is file:///home/lqb/project/FunASR/results/exp/baseline_train_asr_paraformer_conformer_12e_6d_2048_256_zh_char_exp1/ddp_init
stage 5: Inference
run.pl: 2 / 2 failed, log is in /home/lqb/project/FunASR/results/exp/baseline_train_asr_paraformer_conformer_12e_6d_2048_256_zh_char_exp1/decode_asr_transformer_noctc_1best/valid.acc.ave_10best.pb/dev/logdir/asr_inference.*.log
```

**Comment by sister-tong** [comment]
兄弟，你的问题跟我一样

**Comment by LauraGPT** [comment]
The error is the similar to https://github.com/alibaba-damo-academy/FunASR/issues/1011#issuecomment-1763967538. You should install funasr by git clone on you linux server.
