### ISSUE TITLE
导出模型报错

### ISSUE THREAD

**Issue by meiiwohh** [alibaba-damo-academy/FunASR#1050]
python -m funasr.export.export_model --model-name damo/speech_paraformer_asr_nat-aishell1-pytorch --export-dir ./export --type onnx --quantize false

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/funasr/export/export_model.py", line 296, in <module>
    export_model.export(model_name)
  File "/usr/local/lib/python3.10/dist-packages/funasr/export/export_model.py", line 226, in export
    self._export(model, tag_name)
  File "/usr/local/lib/python3.10/dist-packages/funasr/export/export_model.py", line 71, in _export
    self._export_onnx(model, verbose, export_dir)
  File "/usr/local/lib/python3.10/dist-packages/funasr/export/export_model.py", line 239, in _export_onnx
    torch.onnx.export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/funasr/export/models/e2e_asr_paraformer.py", line 68, in forward
    enc, enc_len = self.encoder(**batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/funasr/export/models/encoder/conformer_encoder.py", line 69, in forward
    xs_pad = self.embed(speech)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: Conv2dSubsampling.forward() missing 1 required positional argument: 'x_mask'

Paraformer-aishell，ParaformerBert-aishell，Paraformer-aishell2，ParaformerBert-aishell2这四个模型都导出失败

**Comment by LauraGPT** [comment]
I thank that you export those models above is useless, because they were trained on aishell-1/2. The performance is not good due to the limit training data.

**Comment by meiiwohh** [comment]
针对上述报错，我对源码做了如下修改，可以pass
<img width="597" alt="1" src="https://github.com/alibaba-damo-academy/FunASR/assets/52646545/b79b82db-1d5a-4ee2-b465-e4232a4d09c7">

然后又遇到了此问题：
File "/usr/local/lib/python3.10/dist-packages/funasr/export/models/e2e_asr_paraformer.py", line 72, in forward
    pre_acoustic_embeds, pre_token_length, alphas, pre_peak_index = self.predictor(enc, mask)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Paraformer' object has no attribute 'predictor'

发现Paraformer-aishell等模型model.predictor是CifPredictor类而不是CifPredictorV2类，源码中又没有CifPredictor类对应的CifPredictor_export类，而我用CifPredictorV2_export就可以导出Paraformer-aishell等模型， @LauraGPT 请问我做的这些修改后导出的模型是否正确？
<img width="781" alt="2" src="https://github.com/alibaba-damo-academy/FunASR/assets/52646545/7347c3a4-1a1f-406c-ae41-72bc6ef3892e">
