### ISSUE TITLE
offline infer error with english onnx model

### ISSUE THREAD

**Issue by lixf071213** [alibaba-damo-academy/FunASR#1059]
**issue:**
when i use funasr/runtime/python/onnxruntime/demo_paraformer_offline.py to infer english audio with speech_paraformer-large_asr_nat-en-16k-common-vocab10020-onnx model,i face the following error:
**Error log：**
(funasr231106) lixiufeng@ubuntu:~/asr/funasr/FunASR-main231106/funasr/runtime/python/onnxruntime$ python demo_paraformer_offline.py
Traceback (most recent call last):
  File "demo_paraformer_offline.py", line 15, in <module>
    result = model(wav_path)
  File "/home/lixiufeng/asr/funasr/FunASR-main231106/funasr/runtime/python/onnxruntime/funasr_onnx/paraformer_bin.py", line 115, in __call__
    pred = sentence_postprocess(pred)
  File "/home/lixiufeng/asr/funasr/FunASR-main231106/funasr/runtime/python/onnxruntime/funasr_onnx/utils/postprocess_utils.py", line 225, in sentence_postprocess
    raise ValueError('invalid character: {}'.format(ch))
ValueError: invalid character: ▁he

**my environment details:**
**OS**: ubuntu18.04

**Python Version**：3.8.18

**Package Version**：torch==2.1.0、modelscope==1.9.4、funasr ==0.8.2
**Model**：speech_paraformer-large_asr_nat-en-16k-common-vocab10020-onnx

**Command**：python funasr/runtime/python/onnxruntime/demo_paraformer_offline.py
Thanks.

**Comment by Lizerui9926** [comment]
Please update funasr code and try again, bug has been fixed.

**Comment by lixf071213** [comment]
ok,thank you,bug has been done.
