### ISSUE TITLE
Paraformer finetune error with 'KeyError: 'bpemodel''

### ISSUE THREAD

**Issue by Philshuo** [alibaba-damo-academy/FunASR#1070]
OS:
Ubuntu 20.04 LTS

Python Version：
python 3.8.18

Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
torch2.1.0 torchaudio2.1.0 modelscope1.9.4/1.9.3 funasr0.8.2

Model：
speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch

Command：
python finetune.py

Error log：
~/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch$ python finetune.py 
2023-11-08 22:11:47,343 - modelscope - INFO - PyTorch version 2.1.0 Found.
2023-11-08 22:11:47,343 - modelscope - INFO - Loading ast index from /home/ssr/.cache/modelscope/ast_indexer
2023-11-08 22:11:47,395 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 04480a9fe743187b14b3611fdb56e6ce and a total number of 943 components indexed
2023-11-08 22:11:49,026 - modelscope - INFO - Model revision not specified, use revision: v1.2.1
2023-11-08 22:11:51,014 - modelscope - INFO - Model revision not specified, use revision: v1.2.1
2023-11-08 22:11:51,797 - modelscope - INFO - Set workdir to ./checkpoint
2023-11-08 22:11:52,502 - modelscope - INFO - Model revision not specified, use revision: v1.2.1
Traceback (most recent call last):
  File "/home/ssr/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/ssr/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/trainers/audio/asr_trainer.py", line 102, in __init__
    self.trainer = build_trainer.build_trainer(
  File "/home/ssr/FunASR/funasr/bin/build_trainer.py", line 551, in build_trainer
    bpemodel = modelscope_dict['bpemodel']
KeyError: 'bpemodel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "finetune.py", line 48, in <module>
    modelscope_finetune(params)
  File "finetune.py", line 24, in modelscope_finetune
    trainer = build_trainer(Trainers.speech_asr_trainer, default_args=kwargs)
  File "/home/ssr/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/trainers/builder.py", line 39, in build_trainer
    return build_from_cfg(cfg, TRAINERS, default_args=default_args)
  File "/home/ssr/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "ASRTrainer: 'bpemodel'"

**Comment by LauraGPT** [comment]
Bug has been fixed. You could install modelscope-1.9.3 and funasr-0.8.4

**Comment by Philshuo** [comment]
After updating funasr-0.8.4, I rerun the finetune.py. So far, it seems good!

**Comment by Philshuo** [comment]
Thanks! Very quick!

**Comment by qianzhouyi2** [comment]
same problem occured with modelscope-1.9.5 and funasr-0.8.6(0.8.4 was tried)

**Comment by qianzhouyi2** [comment]
> Bug has been fixed. You could install modelscope-1.9.3 and funasr-0.8.4

same problem occured with modelscope-1.9.5 and funasr-0.8.6(0.8.4 was also tried)
