### ISSUE TITLE
FunASR 0.1.4 AIShell ParaformerBert Baseline Decoing Error

### ISSUE THREAD

**Issue by MrSupW** [alibaba-damo-academy/FunASR#11]
2022-12-10 18:24:02,135 (asr_inference_paraformer:429) INFO: decoding, utt_id: ['BAC009S0746W0278']
2022-12-10 18:24:02,261 (beam_search:1300) INFO: decoder input length: 91
2022-12-10 18:24:02,261 (beam_search:1301) INFO: max output length: 14
2022-12-10 18:24:02,984 (beam_search:1380) INFO: adding <eos> in the last position in the loop
2022-12-10 18:24:02,987 (beam_search:1316) INFO: no hypothesis. Finish decoding.
2022-12-10 18:24:02,987 (beam_search:1337) INFO:  -0.00 * 0.5 =  -0.00 for ctc
2022-12-10 18:24:02,987 (beam_search:1340) INFO: total log probability: -0.98
2022-12-10 18:24:02,987 (beam_search:1341) INFO: normalized log probability: -0.06
2022-12-10 18:24:02,987 (beam_search:1342) INFO: total number of ended hypotheses: 10
2022-12-10 18:24:02,988 (beam_search:1344) INFO: best hypo: 微软今年在中国的重点拓展领域

2022-12-10 18:24:02,988 (asr_inference_paraformer:440) INFO: decoding, feature length: 91, forward_time: 0.8529, rtf: 0.9372
2022-12-10 18:24:02,988 (asr_inference_paraformer:446) INFO: batch_id 0 len(keys) 1 keys ['BAC009S0746W0278']
2022-12-10 18:24:03,057 (asr_inference_paraformer:467) INFO: decoding, utt: BAC009S0746W0278, predictions: 微软今年在中国的重点拓展领域
2022-12-10 18:24:03,057 (asr_inference_paraformer:446) INFO: batch_id 1 len(keys) 1 keys ['BAC009S0746W0278']
Traceback (most recent call last):
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr-main/funasr/bin/asr_inference_launch.py", line 241, in <module>
    main()
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr-main/funasr/bin/asr_inference_launch.py", line 237, in main
    inference_launch(**kwargs)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr-main/funasr/bin/asr_inference_launch.py", line 204, in inference_launch
    return inference(**kwargs)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr-main/funasr/bin/asr_inference_paraformer.py", line 447, in inference
    key = keys[batch_id]
IndexError: list index out of range

I log some value to debug. The length of keys is actually one.

**Comment by MrSupW** [comment]
![image](https://user-images.githubusercontent.com/57617568/206851764-7e7b0532-0b03-4cd3-9d1b-5f86f1c88f7b.png)
I do this modification and everything seems to go well?

**Comment by langgz** [comment]
Your modification is fine. I want to debug you error, what's you batchsize? Only paraformerbert model has error? What about the paraformer model?

**Comment by MrSupW** [comment]
> Your modification is fine. I want to debug you error, what's you batchsize? Only paraformerbert model has error? What about the paraformer model?

gpu_num=2  njob=1
I haven't decode for paraformer model

**Comment by langgz** [comment]
I have not test the decoding with multi-gpu. But I suggest, you could decode with one gpu with batch 128, or with cpu with njob 128, since this would faster.

**Comment by MrSupW** [comment]
> I have not test the decoding with multi-gpu. But I suggest, you could decode with one gpu with batch 128, or with cpu with njob 128, since this would faster.

Ok, I'll try. Thx for the suggestion.
