### ISSUE TITLE
How to call local model.pb using run_service_2pass.sh ?

### ISSUE THREAD

**Issue by Philshuo** [alibaba-damo-academy/FunASR#1114]
OS: Ubuntu 20.04 LTS
Python/C++ Version：python3.8 gcc9.4.0
Package Version：funasr-onnx==0.2.4 torch==2.1.0、modelscope==1.9.5、funasr==0.8.5、torchaudio==2.1.0、onnx==1.15.0、onnxruntime==1.16.3

follow the online docs: https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_online_zh.md
1. Start the docker
2. Start the server:
according to the official commander:
Cmd: root@8d4a098dca2d:/workspace/FunASR/runtime# nohup bash run_server_2pass.sh   --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx   --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx   --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx   --itn-dir thuduj12/fst_itn_zh   --decoder-thread-num 32   --io-thread-num  8   --port 10096   --certfile  0    > log.out 2>&1 &

that's ok.

But when I replace the "--model-dir" with local path "/home/ssr/funasr/funasr11/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/checkpoint/11_17/1/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online", the details as follows:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 26, in <module>
    (model_dir)
TypeError: exceptions must derive from BaseException
I20231123 13:38:54.975768   621 funasr-wss-server-2pass.cpp:268] Failed to download model from modelscope. If you set local asr model path, you can ignore the errors.
E20231123 13:38:54.975818   621 funasr-wss-server-2pass.cpp:277] /workspace/models//home/ssr/funasr/funasr11/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/checkpoint/11_17/1/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model_quant.onnx do not exists.

So, I'm wondering: 
1. Shall I copy the finetune model to the docker dir "$PWD/funasr-runtime-resources/models", then the run_server_2pass.sh can find the correct file?
2. Could you please show me the real commander to start the server with local finetune model?

**Comment by Philshuo** [comment]
There are several steps to complete this process:

1. Export your .onnx file from your model.pb.
2. Replace the relevant file in funasr-runtime-resources/damo/ with the exported .onnx file.
3. Start the Docker.
