### ISSUE TITLE
fintune failed:KeyError: 'bpemodel'

### ISSUE THREAD

**Issue by qianzhouyi2** [alibaba-damo-academy/FunASR#1129]
OS:ubuntu 22.04/20.04

Python Version：python 3.8.18

Package Version：modelscope-1.9.5、funasr-0.8.6、torch-2.1.1、torchaudio-2.1.1

Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：
python finetune.py

2023-11-26 18:42:25,756 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-11-26 18:42:25,756 - modelscope - INFO - Loading ast index from /home/sunrise/.cache/modelscope/ast_indexer
2023-11-26 18:42:25,776 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 d65b78ec60eceab796c1021c3e8a7c85 and a total number of 945 components indexed
2023-11-26 18:42:27,398 - modelscope - WARNING - Model revision not specified, use revision: v1.2.1
2023-11-26 18:42:29,039 - modelscope - WARNING - Model revision not specified, use revision: v1.2.1
2023-11-26 18:42:29,734 - modelscope - INFO - Set workdir to ./checkpoint
2023-11-26 18:42:30,372 - modelscope - WARNING - Model revision not specified, use revision: v1.2.1
Traceback (most recent call last):
  File "/home/sunrise/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/sunrise/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/trainers/audio/asr_trainer.py", line 95, in __init__
    self.cfg_dict = self.parse_cfg(self.model_cfg)
  File "/home/sunrise/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/trainers/audio/asr_trainer.py", line 130, in parse_cfg
    cur_dir, config['model']['model_config']['bpemodel'])
KeyError: 'bpemodel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "finetune.py", line 48, in <module>
    modelscope_finetune(params)
  File "finetune.py", line 24, in modelscope_finetune
    trainer = build_trainer(Trainers.speech_asr_trainer, default_args=kwargs)
  File "/home/sunrise/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/trainers/builder.py", line 39, in build_trainer
    return build_from_cfg(cfg, TRAINERS, default_args=default_args)
  File "/home/sunrise/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "ASRTrainer: 'bpemodel'"

same issues was seen in https://github.com/alibaba-damo-academy/FunASR/issues/1070

**Comment by qianzhouyi2** [comment]
Two computers are configured rightly for infering,both having this problem,so I doubt if there's some kind of library missing.

**Comment by LauraGPT** [comment]
This is a bug, please ref to https://github.com/alibaba-damo-academy/FunASR/issues/1070#issuecomment-1803112146

**Comment by qianzhouyi2** [comment]
That works well,thank you
