### ISSUE TITLE
speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch模型测试错误

### ISSUE THREAD

**Issue by v-yunbin** [alibaba-damo-academy/FunASR#1229]
环境安装：
```
python==3.8.3
torch==1.13.1+cu117
funasr==1.0.0
```
使用模型：
`[https://www.modelscope.cn/models/damo/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary](url)`
参考示例：
`[https://github.com/alibaba-damo-academy/FunASR/blob/funasr1.0/examples/industrial_data_pretraining/seaco_paraformer/demo.py](url)`
完整错误：
```
Traceback (most recent call last):
  File "test_asr_seaco_hotwords.py", line 8, in <module>
    model = AutoModel(model="./speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
  File "/data/disk1/ybZhang/modelscope/asr/FunASR/funasr/bin/inference.py", line 110, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/data/disk1/ybZhang/modelscope/asr/FunASR/funasr/bin/inference.py", line 180, in build_model
    load_pretrained_model(
  File "/data/disk1/ybZhang/modelscope/asr/FunASR/funasr/train_utils/load_pretrained_model.py", line 127, in load_pretrained_model
    obj.load_state_dict(dst_state)
  File "/home/ybZhang/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SeacoParaformer:
        Unexpected key(s) in state_dict: "predictor.blstm.weight_ih_l0", "predictor.blstm.weight_hh_l0", "predictor.blstm.bias_ih_l0", "predictor.blstm.bias_hh_l0", "predictor.blstm.weight_ih_l0_reverse", "predictor.blstm.weight_hh_l0_reverse", "predictor.blstm.bias_ih_l0_reverse", "predictor.blstm.bias_hh_l0_reverse".
        size mismatch for predictor.upsample_cnn.weight: copying a param with shape torch.Size([512, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 5]).
        size mismatch for predictor.cif_output2.weight: copying a param with shape torch.Size([1, 1024]) from checkpoint, the shape in current model is torch.Size([1, 512]).
```

**Comment by LauraGPT** [comment]
We have updated funasr-1.0, maybe you could try it again: 
https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining/seaco_paraformer

**Comment by v-yunbin** [comment]
> We have updated funasr-1.0, maybe you could try it again: https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining/seaco_paraformer

@LauraGPT 还是报同样的错。

**Comment by R1ckShi** [comment]
删除你的模型的本地缓存，重新装一下funasr环境吧，从来没有遇到过这个问题哈
