### ISSUE TITLE
出现：AutomaticSpeechRecognitionPipeline: cannot import name 'asr_inference_launch' from 'funasr.bin'

### ISSUE THREAD

**Issue by White-Friday** [alibaba-damo-academy/FunASR#1240]
问题在下楼

**Comment by White-Friday** [comment]
@LauraGPT 请问funasr推理paraformer的速度和modelscope推理的速度之间有多大的差距

**Comment by White-Friday** [comment]
@LauraGPT 另外还有一个问题
使用你给的代码：
```python
from funasr import AutoModel

model = AutoModel(model="damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
                  #model_revision="v1.2.4",
                  #vad_model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                  #vad_model_revision="v2.0.1",
                  #punc_model="damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch",
                  #punc_model_revision="v2.0.0",
                  #spk_model="damo/speech_campplus_sv_zh-cn_16k-common",
                  #spk_model_revision="v2.0.0"
                  )

res = model(input="asr_example_zh.wav",
            hotword='达摩院 磨搭')
print(res)
```
出现下面的报错，自己debug，请问源码里面需要修改哪个部分的代码，将跑在cpu上的转到gpu
```python
Traceback (most recent call last):
  File "/data/xxx/speech_text/infer_vad.py", line 34, in <module>
    res = model(input="asr_example_zh.wav",
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/bin/inference.py", line 196, in __call__
    return self.generate(input, input_len=input_len, **cfg)
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/bin/inference.py", line 232, in generate
    results, meta_data = model.generate(**batch, **kwargs).to("cuda:0")
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/models/bicif_paraformer/model.py", line 258, in generate
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/models/paraformer/model.py", line 267, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(speech, speech_lengths)
  File "/home/xxx/anaconda3/envs/paraformer/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/models/sanm/encoder.py", line 370, in forward
    encoder_outs = self.encoders0(xs_pad, masks)
  File "/home/xxx/anaconda3/envs/paraformer/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/models/transformer/utils/repeat.py", line 32, in forward
    args = m(*args)
  File "/home/xxx/anaconda3/envs/paraformer/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/models/sanm/encoder.py", line 91, in forward
    x = self.norm1(x)
  File "/home/xxx/anaconda3/envs/paraformer/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xxx/speech_text/FunASR-funasr1.0/funasr/models/transformer/layer_norm.py", line 38, in forward
    return super(LayerNorm, self).forward(x)
  File "/home/xxx/anaconda3/envs/paraformer/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/home/xxx/anaconda3/envs/paraformer/lib/python3.10/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)
python

谢谢

**Comment by HelloTheWholeWorld** [comment]
请问作者解决了AutomaticSpeechRecognitionPipeline: cannot import name 'asr_inference_launch' from 'funasr.bin'这个问题吗？谢谢

**Comment by White-Friday** [comment]
@HelloTheWholeWorld 更新到funasr1.0.0，(https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0)

**Comment by herolj** [comment]
请问解决了吗？ 我用pycharm工具运行就报这错，直接在终端python 运行就正常。
百思不得其解。。

**Comment by LauraGPT** [comment]
> 我用pycharm工具运行就报这错，直接在终端p

modelscope-1.11.1
funasr-1.0.2

**Comment by LRY1994** [comment]
> > 我用pycharm工具运行就报这错，直接在终端p
> 
> modelscope-1.11.1 funasr-1.0.2

KeyError: 'asr-inference is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

**Comment by LRY1994** [comment]
> ```shell
> pip install -e ./
> ```

为啥404了

**Comment by liyhc** [comment]
I tried `pip  install funasr==0.7` and it worked for me.
