### ISSUE TITLE
ImportError: cannot import name 'asr_utils' from 'funasr.utils'

### ISSUE THREAD

**Issue by zhongqiu1245** [alibaba-damo-academy/FunASR#1262]
## 🐛 Bug

ImportError: cannot import name 'asr_utils' from 'funasr.utils'     （in  FunASR/funasr/utils/__init__.py）

### To Reproduce
```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

infer_pipeline = pipeline(
    task=Tasks.speech_timestamp,
    model='damo/speech_timestamp_prediction-v1-16k-offline',
    model_revision='v1.1.0'
)
rec_result = infer_pipeline(
    audio_in='asr_example_timestamps.wav',
    text_in='一 个 东 太 平 洋 国 家 为 什 么 跑 到 西 太 平 洋 来 了 呢'
)
print(rec_result)

Traceback (most recent call last):
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/msWorkShop/FunASR/001.py", line 4, in <module>
    infer_pipeline = pipeline(
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mcsph/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mcsph/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mcsph/lib/python3.10/site-packages/modelscope/utils/registry.py", line 184, in build_from_cfg
    LazyImportModule.import_module(sig)
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mcsph/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 475, in import_module
    importlib.import_module(module_name)
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mcsph/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mcsph/lib/python3.10/site-packages/modelscope/pipelines/audio/timestamp_pipeline.py", line 7, in <module>
    from funasr.utils import asr_utils
ImportError: cannot import name 'asr_utils' from 'funasr.utils' (/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/msWorkShop/FunASR/funasr/utils/__init__.py)
```

### Environment

 - OS (e.g., Linux): Ubuntu 22.04
 - FunASR Version (e.g., 1.0.0): main 1.0.0
 - ModelScope Version (e.., 1.11.0):1.11.0
 - PyTorch Version (e.g., 2.0.0): 2.1.0
 - How you installed funasr (`pip`, source): source
 - Python version: 3.10
 - GPU (e.g., V100M32): 4060
 - CUDA/cuDNN version (e.g., cuda11.7): 12.1
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1) None
 - Any other relevant information: None

**Comment by LauraGPT** [comment]
需要更新funasr1.0，
更新方法：
git clone -b main --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
pip install -e ./

新的用法：
https://github.com/alibaba-damo-academy/FunASR?tab=readme-ov-file#quick-start

**Comment by zhongqiu1245** [comment]
Thank you！
