### ISSUE TITLE
AttributeError: FunASRPipeline: GenericFunASR: 'CharTokenizer' object has no attribute 'token_list'

### ISSUE THREAD

**Issue by Jun2Hou** [alibaba-damo-academy/FunASR#1300]
## 🐛 Bug
AttributeError: FunASRPipeline: GenericFunASR: 'CharTokenizer' object has no attribute 'token_list'

### To Reproduce
1. Run python
get error by running  pipeline as follows:

path_asr='tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'
path_vad='tools/damo_asr/models/speech_fsmn_vad_zh-cn-16k-common-pytorch'
path_punc='tools/damo_asr/models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch'

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model=path_asr,
    vad_model=path_vad,
    punc_model=path_punc,
)

3. See error
2024-01-24 19:17:58,650 - modelscope - INFO - PyTorch version 2.1.2 Found.
2024-01-24 19:17:58,651 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-01-24 19:17:58,670 - modelscope - INFO - Updating the files for the changes of local files, first time updating will take longer time! Please wait till updating done!
2024-01-24 19:17:58,678 - modelscope - INFO - AST-Scanning the path "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope" with the following sub folders ['models', 'metrics', 'pipelines', 'preprocessors', 'trainers', 'msdatasets', 'exporters']
2024-01-24 19:18:07,792 - modelscope - INFO - Scanning done! A number of 956 components indexed or updated! Time consumed 9.113605737686157s
2024-01-24 19:18:07,813 - modelscope - INFO - Loading done! Current index file version is 1.11.1, with md5 6647d0be8013b72c9258053cf78c15b2 and a total number of 956 components indexed
2024-01-24 19:18:08,377 - modelscope - INFO - initiate model from tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-24 19:18:08,377 - modelscope - INFO - initiate model from location tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-01-24 19:18:08,377 - modelscope - INFO - initialize model from tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch

tables:

----------- ** dataset_classes ** --------------
| class name | class location |
| AudioDataset | funasr/datasets/audio_datasets/datasets.py:7 |
----------- ** index_ds_classes ** --------------
| class name | class location |
| IndexDSJsonl | funasr/datasets/audio_datasets/index_ds.py:9 |
----------- ** batch_sampler_classes ** --------------
| class name | class location |
| BatchSampler | funasr/datasets/audio_datasets/samplers.py:7 |
----------- ** frontend_classes ** --------------
| class name | class location |
| WavFrontend | funasr/frontends/wav_frontend.py:78 |
| WavFrontendOnline | funasr/frontends/wav_frontend.py:216 |
----------- ** encoder_classes ** --------------
| class name | class location |
| BranchformerEncoder | funasr/models/branchformer/encoder.py:294 |
| ConformerChunkEncoder | funasr/models/bat/conformer_chunk_encoder.py:315 |
| ConformerEncoder | funasr/models/conformer/encoder.py:286 |
| DFSMN | funasr/models/fsmn_vad_streaming/encoder.py:232 |
| EBranchformerEncoder | funasr/models/e_branchformer/encoder.py:177 |
| FSMN | funasr/models/fsmn_vad_streaming/encoder.py:161 |
| SANMEncoder | funasr/models/sanm/encoder.py:161 |
| SANMEncoderChunkOpt | funasr/models/scama/encoder.py:162 |
| SANMVadEncoder | funasr/models/ct_transformer_streaming/encoder.py:148 |
| TransformerEncoder | funasr/models/transformer/encoder.py:139 |
----------- ** predictor_classes ** --------------
| class name | class location |
| CifPredictor | funasr/models/paraformer/cif_predictor.py:15 |
| CifPredictorV2 | funasr/models/paraformer/cif_predictor.py:141 |
| CifPredictorV3 | funasr/models/bicif_paraformer/cif_predictor.py:95 |
----------- ** model_classes ** --------------
| class name | class location |
| BiCifParaformer | funasr/models/bicif_paraformer/model.py:37 |
| Branchformer | funasr/models/branchformer/model.py:6 |
| CAMPPlus | funasr/models/campplus/model.py:30 |
| CTTransformer | funasr/models/ct_transformer/model.py:30 |
| CTTransformerStreaming | funasr/models/ct_transformer_streaming/model.py:27 |
| Conformer | funasr/models/conformer/model.py:8 |
| ContextualParaformer | funasr/models/contextual_paraformer/model.py:43 |
| EBranchformer | funasr/models/e_branchformer/model.py:6 |
| Emotion2vec | funasr/models/emotion2vec/model.py:34 |
| FsmnVADStreaming | funasr/models/fsmn_vad_streaming/model.py:267 |
| MonotonicAligner | funasr/models/monotonic_aligner/model.py:24 |
| Paraformer | funasr/models/paraformer/model.py:26 |
| ParaformerStreaming | funasr/models/paraformer_streaming/model.py:37 |
| SANM | funasr/models/sanm/model.py:13 |
| SCAMA | funasr/models/scama/model.py:38 |
| SeacoParaformer | funasr/models/seaco_paraformer/model.py:45 |
| Transformer | funasr/models/transformer/model.py:20 |
| UniASR | funasr/models/uniasr/model.py:25 |
----------- ** decoder_classes ** --------------
| class name | class location |
| ContextualParaformerDecoder | funasr/models/contextual_paraformer/decoder.py:103 |
| DynamicConvolution2DTransformerDecoder | funasr/models/transformer/decoder.py:588 |
| DynamicConvolutionTransformerDecoder | funasr/models/transformer/decoder.py:527 |
| FsmnDecoder | funasr/models/sanm/decoder.py:198 |
| FsmnDecoderSCAMAOpt | funasr/models/scama/decoder.py:197 |
| LightweightConvolution2DTransformerDecoder | funasr/models/transformer/decoder.py:465 |
| LightweightConvolutionTransformerDecoder | funasr/models/transformer/decoder.py:404 |
| ParaformerSANDecoder | funasr/models/paraformer/decoder.py:529 |
| ParaformerSANMDecoder | funasr/models/paraformer/decoder.py:204 |
| TransformerDecoder | funasr/models/transformer/decoder.py:355 |
----------- ** normalize_classes ** --------------
| class name | class location |
| GlobalMVN | funasr/models/normalize/global_mvn.py:11 |
| UtteranceMVN | funasr/models/normalize/utterance_mvn.py:8 |
----------- ** specaug_classes ** --------------
| class name | class location |
| SpecAug | funasr/models/specaug/specaug.py:14 |
| SpecAugLFR | funasr/models/specaug/specaug.py:104 |
----------- ** tokenizer_classes ** --------------
| class name | class location |
| CharTokenizer | funasr/tokenizer/char_tokenizer.py:10 |
| SentencepiecesTokenizer | funasr/tokenizer/sentencepiece_tokenizer.py:11 |

Traceback (most recent call last):
File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
return obj_cls._instantiate(**args)

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/base/base_model.py", line 67, in _instantiate
return cls(**kwargs)

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/audio/funasr/model.py", line 55, in init
self.model = AutoModel(model=model_dir, **kwargs)

File "/root/anaconda3/envs/bs/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 93, in init
model, kwargs = self.build_model(**kwargs)

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 163, in build_model
kwargs["token_list"] = tokenizer.token_list

AttributeError: 'CharTokenizer' object has no attribute 'token_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
return obj_cls(**args)

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/audio/funasr_pipeline.py", line 62, in init
super().init(model=model, **kwargs)
File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/base.py", line 100, in init
self.model = self.initiate_single_model(model, **kwargs)

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/base.py", line 53, in initiate_single_model
return Model.from_pretrained(

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/base/base_model.py", line 183, in from_pretrained
model = build_model(model_cfg, task_name=task_name)

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/builder.py", line 35, in build_model
model = build_from_cfg(

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
raise type(e)(f'{obj_cls.name}: {e}')
AttributeError: GenericFunASR: 'CharTokenizer' object has no attribute 'token_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/user/aaa/GPT-SoVITS/tools/damo_asr/cmd-asr.py", line 16, in
inference_pipeline = pipeline(

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
return build_pipeline(cfg, task_name=task)

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
return build_from_cfg(

File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
raise type(e)(f'{obj_cls.name}: {e}')
AttributeError: FunASRPipeline: GenericFunASR: 'CharTokenizer' object has no attribute 'token_list'

### Environment
 - OS: Linux
 - FunASR Version: 1.0.2; tried install from github 
 - ModelScope Version: 1.11.1; tried 1.10, 1.14 version
 - PyTorch Version: 2.1.2
 - How you installed funasr: pip install funasr
 - Python version: test on 3.10.0 & 3.11
 - GPU (3080ti)
 - CUDA/cuDNN version (cuda12.1):

**Comment by LauraGPT** [comment]
If your envs: modelscope-1.11.1, funasr-1.0.2
You could use the pipeline:
```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', model_revision="v2.0.4",
    vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
    punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision="v2.0.4",
)

rec_result = inference_pipeline('https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
print(rec_result)
```

I think your error is the that models downloaded is too old. You could re-download it again.

**Comment by Jun2Hou** [comment]
> from modelscope.pipelines import pipeline
> from modelscope.utils.constant import Tasks
> 
> inference_pipeline = pipeline(
>     task=Tasks.auto_speech_recognition,
>     model='iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', model_revision="v2.0.4",
>     vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
>     punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision="v2.0.4",
> )
> 
> rec_result = inference_pipeline('https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
> print(rec_result)

@LauraGPT the above given code works and appreciated. 
Regarding to models downloaded in my case, I used "git clone https://www.modelscope.cn/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.git" that is update-to-date. Just wondering how to get latest model? do I need to update funasr & modelscope as well?

**Comment by LauraGPT** [comment]
> > from modelscope.pipelines import pipeline
> > from modelscope.utils.constant import Tasks
> > inference_pipeline = pipeline(
> > task=Tasks.auto_speech_recognition,
> > model='iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', model_revision="v2.0.4",
> > vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
> > punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision="v2.0.4",
> > )
> > rec_result = inference_pipeline('https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
> > print(rec_result)
> 
> @LauraGPT the above given code works and appreciated. Regarding to models downloaded in my case, I used "git clone https://www.modelscope.cn/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.git" that is update-to-date. Just wondering how to get latest model? do I need to update funasr & modelscope as well?

to download models by `git clone` is ok. But you need to re-download them again, today.
