### ISSUE TITLE
长音频模型 加上说话人识别模型(spk_model)之后报错

### ISSUE THREAD

**Issue by jpyjpr** [alibaba-damo-academy/FunASR#1302]
### 执行代码：

```Python
from funasr import AutoModel
model = AutoModel(model="paraformer-zh", model_revision="v2.0.4", \
                  vad_model="/workspace/model/download/speech_fsmn_vad_zh-cn-16k-common-pytorch", vad_model_revision="v2.0.4", \
                  punc_model="/workspace/model/download/punc_ct-transformer_zh-cn-common-vocab272727-pytorch", punc_model_revision="v2.0.4",\
                  spk_model="cam++", spk_model_revision="v2.0.2",
                    )
res = model.generate(input=f"/workspace/data/bl_1_773-813.wav", 
                     batch_size=64)
print(res)
```

报错信息是：
```Shell
Traceback (most recent call last):eech_total_per_sample:  40.000, time_escape_total_per_sample: 0.468:  83%|█████▊ | 5/6 [00:00<00:00, 10.68it/s]
  File "run.py", line 47, in <module>█████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 114.14it/s]
    res = model.generate(input=f"/workspace/data/bl_1_773-813.wav", 
  File "/workspace/FunASR-main/funasr/auto/auto_model.py", line 208, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "/workspace/FunASR-main/funasr/auto/auto_model.py", line 399, in inference_with_vad
    labels = self.cb_model(spk_embedding, oracle_num=self.preset_spk_num)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/FunASR-main/funasr/models/campplus/cluster_backend.py", line 159, in forward
    labels = self.spectral_cluster(X, k)
  File "/workspace/FunASR-main/funasr/models/campplus/cluster_backend.py", line 29, in __call__
    sim_mat = self.get_sim_mat(X)
  File "/workspace/FunASR-main/funasr/models/campplus/cluster_backend.py", line 50, in get_sim_mat
    M = sklearn.metrics.pairwise.cosine_similarity(X, X)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 1578, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 149, in check_pairwise_arrays
    X, Y, dtype_float = _return_float_dtype(X, Y)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 55, in _return_float_dtype
    X = np.asarray(X)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 970, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
  0%|                                                                                                                      | 0/2 [00:00<?, ?it/s]
rtf_avg_per_sample: 0.012, time_speech_total_per_sample:  40.000, time_escape_total_per_sample: 0.468:  83%|█████▊ | 5/6 [00:00<00:00,  8.91it/s]

```

**Comment by LauraGPT** [comment]
Bug has been fixed. Please update funasr-1.0.2, and try it again.

**Comment by jpyjpr** [comment]
> 错误已修复。请更新funasr-1.0.2，然后重试。

你好，我更新1.0.2之后发现模型正常跑了，但是没有使用gpu、之前1.0.0是有用gpu的，我试了t4 和 4090都是一样的结果。新版本是需要单独设置参数吗？

**Comment by lmxin123** [comment]
请问你是使用FunASR模型吗，我发现FunASR没有spk_model这个参数。

**Comment by jpyjpr** [comment]
> 请问你是使用FunASR模型吗，我发现FunASR没有spk_model这个参数。

对 我用的是funasr框架 是有spk_model参数的，你更新代码试试

**Comment by lmxin123** [comment]
> > 请问你是使用FunASR模型吗，我发现FunASR没有spk_model这个参数。
> 
> 对 我用的是funasr框架 是有spk_model参数的，你更新代码试试

是这个链接吗？https://github.com/alibaba-damo-academy/FunASR  我看你上在聊的版本是1.0.2。funasr 最新版本不是4.4吗？
方便发一下你使用的版本链接不？

**Comment by lmxin123** [comment]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/12029452/442cf9a1-91b8-4445-b0d7-d72cc54c612d)
我看这里都没spk_model参数
