### ISSUE TITLE
TypeError: FunASRPipeline: GenericFunASR: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by qx220** [alibaba-damo-academy/FunASR#1334]
## 🐛 Bug

When running the the app containing the following code (directly copied from https://modelscope.cn/models/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary)

```python
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    model_revision="v2.0.4")

```

the current version of funasr produces the following error

```
2024-02-01 00:08:25,511 - modelscope - INFO - PyTorch version 2.2.0+cpu Found.
2024-02-01 00:08:25,512 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-02-01 00:08:25,807 - modelscope - INFO - Loading done! Current index file version is 1.11.1, with md5 56dde6840f1b32f93d591290253a7ec0 and a total number of 956 components indexed
/usr/local/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2024-02-01 00:08:27,596 - modelscope - INFO - Use user-specified model revision: v2.0.4
2024-02-01 00:08:28,098 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-02-01 00:08:28,098 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-02-01 00:08:28,100 - modelscope - INFO - initialize model from /root/.cache/modelscope/hub/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-02-01 00:08:33,455 - modelscope - WARNING - Model revision not specified, use revision: v2.0.0
Please Requires the ffmpeg CLI and `ffmpeg-python` package to be installed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/usr/local/lib/python3.9/site-packages/modelscope/models/base/base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/modelscope/models/audio/funasr/model.py", line 55, in __init__
    self.model = AutoModel(model=model_dir, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 102, in __init__
    vad_model, vad_kwargs = self.build_model(**vad_kwargs)
  File "/usr/local/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 176, in build_model
    model = model_class(**kwargs, **kwargs["model_conf"], vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/lib/python3.9/site-packages/modelscope/pipelines/audio/funasr_pipeline.py", line 62, in __init__
    super().__init__(model=model, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/modelscope/pipelines/base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/modelscope/pipelines/base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "/usr/local/lib/python3.9/site-packages/modelscope/models/base/base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "/usr/local/lib/python3.9/site-packages/modelscope/models/builder.py", line 35, in build_model
    model = build_from_cfg(
  File "/usr/local/lib/python3.9/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: GenericFunASR: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 16, in <module>
    inference_pipeline = pipeline(task=Tasks.auto_speech_recognition, model = 'iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch', model_revision="v2.0.4", device='cpu')
  File "/usr/local/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/usr/local/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/usr/local/lib/python3.9/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FunASRPipeline: GenericFunASR: 'NoneType' object is not callable
```

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

Run the following code:

```python
from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    model_revision="v2.0.4")
```

### Environment

 - OS (e.g., Linux): Fedora 38
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
```
root@54ebbbf0541d:/app# pip show funasr modelscope torch
Name: funasr
Version: 1.0.5
Summary: FunASR: A Fundamental End-to-End Speech Recognition Toolkit
Home-page: https://github.com/alibaba-damo-academy/FunASR.git
Author: Speech Lab of Alibaba Group
Author-email: funasr@list.alibaba-inc.com
License: The MIT License
Location: /usr/local/lib/python3.9/site-packages
Requires: editdistance, hdbscan, hydra-core, jaconv, jamo, jieba, kaldiio, librosa, oss2, pytorch-wpe, PyYAML, scipy, sentencepiece, torch-complex, tqdm, umap-learn
Required-by: 
---
Name: modelscope
Version: 1.11.1
Summary: ModelScope: bring the notion of Model-as-a-Service to life.
Home-page: https://github.com/modelscope/modelscope
Author: ModelScope team
Author-email: contact@modelscope.cn
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: addict, attrs, datasets, einops, filelock, gast, numpy, oss2, pandas, Pillow, pyarrow, python-dateutil, pyyaml, requests, scipy, setuptools, simplejson, sortedcontainers, tqdm, urllib3, yapf
Required-by: 
---
Name: torch
Version: 2.2.0+cpu
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.9/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: rotary-embedding-torch, torchaudio, torchvision
```
 - How you installed funasr (`pip`, source): pip
 - Python version: 3.9
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by qx220** [comment]
After testing, it seems like that the issue is on the specific model `iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch`

**Comment by Svellsongur6** [comment]
有人解决了吗，我应该如何修改呢？

**Comment by qx220** [comment]
> 有人解决了吗，我应该如何修改呢？

加上vad这些模型的kwargs就可以，目前我是用这个workaround：

```python
model = AutoModel(
    task=Tasks.auto_speech_recognition,
    model = 'iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    model_revision="v2.0.4",
    vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
    punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision="v2.0.4",
)

```

**Comment by LauraGPT** [comment]
Please use it as [demo](https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/bicif_paraformer/demo.py)

**Comment by jinqinn** [comment]
'NoneType' object is not callable

一直报错，真是搞不明白了

**Comment by YuanJie2001** [comment]
> > 有人解决了吗，我应该如何修改呢？
> 
> 加上vad这些模型的kwargs就可以，目前我是用这个workaround：
> 
> model = AutoModel(
>     task=Tasks.auto_speech_recognition,
>     model = 'iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
>     model_revision="v2.0.4",
>     vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
>     punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision="v2.0.4",
> )

你这里的model怎么了多了seaco

**Comment by YuanJie2001** [comment]
你没解决，你是换模型了吧。。。
