### ISSUE TITLE
TypeError: GenericFunASR: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by xuzhitong89** [alibaba-damo-academy/FunASR#1354]
windos 下 使用funasr-1.0.2  modelscope-1.11.1版本报错如下

Traceback (most recent call last):
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
           ^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\pipelines\audio\funasr_pipeline.py", line 62, in __init__
    super().__init__(model=model, **kwargs)
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\pipelines\base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
            ^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: GenericFunASR: 'NoneType' object is not callable

**Comment by xuzhitong89** [comment]
Traceback (most recent call last):
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\utils\registry.py", line 211, in build_from_cfg
    return obj_cls._instantiate(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\models\base\base_model.py", line 67, in _instantiate
    return cls(**kwargs)
           ^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\models\audio\funasr\model.py", line 55, in __init__
    self.model = AutoModel(model=model_dir, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\pycharmprojects\funasr-main-new\funasr-main\funasr\auto\auto_model.py", line 102, in __init__
    vad_model, vad_kwargs = self.build_model(**vad_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\pycharmprojects\funasr-main-new\funasr-main\funasr\auto\auto_model.py", line 176, in build_model
    model = model_class(**kwargs, **kwargs["model_conf"], vocab_size=vocab_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\utils\registry.py", line 213, in build_from_cfg
    return obj_cls(**args)
           ^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\pipelines\audio\funasr_pipeline.py", line 62, in __init__
    super().__init__(model=model, **kwargs)
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\pipelines\base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
            ^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main-new\Lib\site-packages\modelscope\utils\registry.py", line 219, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: GenericFunASR: 'NoneType' object is not callable

**Comment by LauraGPT** [comment]
Solution: https://github.com/alibaba-damo-academy/FunASR/discussions/1319
