### ISSUE TITLE
Exception: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by deyiluobo** [alibaba-damo-academy/FunASR#1361]
## 🐛 Bug
Follow the tutorial below for service deployment
[服务器部署](https://alibaba-damo-academy.github.io/FunASR/en/funasr/quick_start.html#server-deployment)
Deployed the service using python, tested it using python client, and encountered a bug

### To Reproduce
server:
python funasr_wss_server.py --port 10095

client:
python funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in ~/ASRData/asr_example.wav

**then see error:**
server:
new user connected
Exception: 'list' object has no attribute 'split'

client:
Namespace(audio_fs=16000, audio_in='/home/dzy/ASRData/asr_example.wav', chunk_interval=10, chunk_size=[5, 10, 5], decoder_chunk_look_back=0, encoder_chunk_look_back=4, host='127.0.0.1', hotword='', mode='offline', output_dir=None, port=10095, send_without_sleep=True, ssl=1, thread_num=1, use_itn=1, words_max_print=10000)
connect to wss://127.0.0.1:10095
Exception: received 1000 (OK); then sent 1000 (OK)
Process Process-1:
Traceback (most recent call last):
  File "/home/dzy/miniforge3/envs/funasr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dzy/miniforge3/envs/funasr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "funasr_wss_client.py", line 368, in one_thread
    asyncio.get_event_loop().run_until_complete(ws_client(id, chunk_begin, chunk_size))
  File "/home/dzy/miniforge3/envs/funasr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "funasr_wss_client.py", line 363, in ws_client
    await asyncio.gather(task, task3)
  File "funasr_wss_client.py", line 249, in record_from_scp
    await websocket.send(message)
  File "/home/dzy/miniforge3/envs/funasr/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/home/dzy/miniforge3/envs/funasr/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
end

### Environment

 - OS: Linux
 - FunASR 1.0.5:
 - ModelScope  1.11.1
 - torch  1.13.1+cu117
 - How you installed funasr (`pip`, source):source
 - Python version:3.8.18
 - GPU 3060
 - CUDA/cuDNN version11.7
 - Docker version 24.0.2
 - Any other relevant information:

**Comment by deyiluobo** [comment]
The bug disappears after reinstalling funasr
