### ISSUE TITLE
离线paraformer推理报错

### ISSUE THREAD

**Issue by dospeech** [alibaba-damo-academy/FunASR#1432]
##  Help
3.5号刚git clone的新代码，运行infer.shhou 报错，不知道什么原因，情况如下：

root@9df7eea98999:/workspace/20240305_funasr/FunASR/examples/industrial_data_pretraining/paraformer# ./infer.sh 

If you want to use hugging, please `pip install -U transformers`
/usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'funasr.bin.inference' found in sys.modules after import of package 'funasr.bin', but prior to execution of 'funasr.bin.inference'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[2024-03-05 13:20:05,566][root][INFO] - download models from model hub: ms
[2024-03-05 13:20:11,621][root][INFO] - Loading pretrained params from exp/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt
ckpt: exp/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt
Error executing job with overrides: ['++model=exp/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch', '++model_revision=v2.0.4', '++input=exp/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/example/asr_example.wav', '++output_dir=./outputs/debug', '++device=cuda:0']
Traceback (most recent call last):
  File "/workspace/20240305_funasr/FunASR/funasr/bin/inference.py", line 25, in main_hydra
    model = AutoModel(**kwargs)
  File "/workspace/20240305_funasr/FunASR/funasr/auto/auto_model.py", line 102, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/workspace/20240305_funasr/FunASR/funasr/auto/auto_model.py", line 191, in build_model
    load_pretrained_model(
  File "/workspace/20240305_funasr/FunASR/funasr/train_utils/load_pretrained_model.py", line 68, in load_pretrained_model
    src_state = torch.load(path, map_location=map_location)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

#########. infer.sh Code 如下：
input="exp/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/example/asr_example.wav"

output_dir="./outputs/debug"

#model="exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
model="exp/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
model_revision="v2.0.4"

device="cuda:0" # "cuda:0" for gpu0, "cuda:1" for gpu1, "cpu"

python -m funasr.bin.inference \
++model=${model} \
++model_revision=${model_revision} \
++input="${input}" \
++output_dir="${output_dir}" \
++device="${device}" \

#### What have you tried?
只改变音频输入路径
#### What's your environment?

 - OS :Debian GNU/Linux 10 (buster)
 - FunASR Version (1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version :1.13.0+cu117
 - How you installed funasr (`pip`, source): https://pypi.tuna.tsinghua.edu.cn/simple
 - Python version:Python 3.8.10
 - GPU (e.g., V100M32)：V100M32

 - Any other relevant information:

**Comment by LauraGPT** [comment]
Please check your model path.
