### ISSUE TITLE
damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020 推理报错

### ISSUE THREAD

**Issue by ZhinanWu** [alibaba-damo-academy/FunASR#1446]
## 🐛 Bug

使用长音频离线英文版推理报错

脚本文件为：

`
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    output_dir='./outputs')

inference_pipeline(audio_in="./myhb.wav")
`

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. 在conda环境下执行python main.py,将使用audio_in参数

报错信息为：
`
2024-03-07 10:33:06,564 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-03-07 10:33:06,564 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-03-07 10:33:06,592 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 15928bc22e3de68c7bf1a1e5c99158aa and a total number of 964 components indexed
2024-03-07 10:33:07,837 - modelscope - WARNING - Model revision not specified, use revision: v2.0.4
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 1.14MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 173k/173k [00:00<00:00, 1.86MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.45k/2.45k [00:00<00:00, 1.59MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<00:00, 297kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 840M/840M [00:39<00:00, 22.0MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19.1k/19.1k [00:00<00:00, 645kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.90M/7.90M [00:01<00:00, 7.63MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48.7k/48.7k [00:00<00:00, 818kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 91.5k/91.5k [00:00<00:00, 1.59MB/s]
2024-03-07 10:33:52,536 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-03-07 10:33:52,536 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-03-07 10:33:52,537 - modelscope - INFO - initialize model from /root/.cache/modelscope/hub/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
If you want to use hugging, please `pip install -U transformers`
ckpt: /root/.cache/modelscope/hub/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt
2024-03-07 10:33:58,035 - modelscope - WARNING - No preprocessor field found in cfg.
2024-03-07 10:33:58,035 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-03-07 10:33:58,035 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/root/.cache/modelscope/hub/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'}. trying to build by task and model information.
2024-03-07 10:33:58,035 - modelscope - WARNING - No preprocessor key ('funasr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    inference_pipeline(audio_in="./myhb.wav")
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/pipelines/audio/funasr_pipeline.py", line 73, in __call__
    output = self.model(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/models/base/base_model.py", line 35, in __call__
    return self.postprocess(self.forward(*args, **kwargs))
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/models/audio/funasr/model.py", line 61, in forward
    output = self.model.generate(*args, **kwargs)
TypeError: generate() missing 1 required positional argument: 'input'

`

2. 将参数改为input
  报错信息为：
`
python main.py                                                                                                                                           (funasr-rst)
2024-03-07 10:29:06,564 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-03-07 10:29:06,565 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-03-07 10:29:06,592 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 15928bc22e3de68c7bf1a1e5c99158aa and a total number of 964 components indexed
2024-03-07 10:29:07,819 - modelscope - INFO - Use user-specified model revision: v2.0.2
2024-03-07 10:29:08,026 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020
2024-03-07 10:29:08,026 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020.
2024-03-07 10:29:08,027 - modelscope - INFO - initialize model from /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020
If you want to use hugging, please `pip install -U transformers`
ckpt: /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020/model.pt
2024-03-07 10:29:14,044 - modelscope - WARNING - Model revision not specified, use revision: v2.0.4
ckpt: /root/.cache/modelscope/hub/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt
2024-03-07 10:29:14,595 - modelscope - WARNING - Model revision not specified, use revision: v2.0.4
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.00k/6.00k [00:00<00:00, 623kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 810/810 [00:00<00:00, 483kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 373/373 [00:00<00:00, 222kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 278M/278M [00:33<00:00, 8.71MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 863/863 [00:00<00:00, 614kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11.2k/11.2k [00:00<00:00, 6.27MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 151k/151k [00:00<00:00, 2.02MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.01M/4.01M [00:00<00:00, 5.83MB/s]
ckpt: /root/.cache/modelscope/hub/iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch/model.pt
2024-03-07 10:29:52,799 - modelscope - WARNING - Model revision not specified, use revision: v2.0.2
ckpt: /root/.cache/modelscope/hub/iic/speech_campplus_sv_zh-cn_16k-common/campplus_cn_common.bin
2024-03-07 10:29:53,239 - modelscope - WARNING - No preprocessor field found in cfg.
2024-03-07 10:29:53,239 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-03-07 10:29:53,239 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020'}. trying to build by task and model information.
2024-03-07 10:29:53,239 - modelscope - WARNING - No preprocessor key ('funasr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
rtf_avg: 0.567: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:16<00:00, 16.26s/it]
  0%|                                                                                                                                                                            | 0/1 [00:00<?, ?it/sTraceback (most recent call last):                                                                                                                                              | 0/247 [00:00<?, ?it/s]
  File "main.py", line 11, in <module>
    inference_pipeline(input="./myhb.wav")
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/pipelines/audio/funasr_pipeline.py", line 73, in __call__
    output = self.model(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/models/base/base_model.py", line 35, in __call__
    return self.postprocess(self.forward(*args, **kwargs))
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/models/audio/funasr/model.py", line 61, in forward
    output = self.model.generate(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/auto/auto_model.py", line 215, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/auto/auto_model.py", line 338, in inference_with_vad
    results = self.inference(speech_j, input_len=None, model=model, kwargs=kwargs, **cfg)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/auto/auto_model.py", line 248, in inference
    res = model.inference(**batch, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/models/paraformer/model.py", line 481, in inference
    predictor_outs = self.calc_predictor(encoder_out, encoder_out_lens)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/models/paraformer/model.py", line 272, in calc_predictor
    pre_acoustic_embeds, pre_token_length, alphas, pre_peak_index = self.predictor(encoder_out, None,
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/models/paraformer/cif_predictor.py", line 179, in forward
    output = torch.relu(self.cif_conv1d(queries))
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Invalid argument
  0%|                                                                                                                                                                          | 0/247 [00:02<?, ?it/s]
  0%|                                                                                                                                                                            | 0/1 [00:02<?, ?it/s]
root@8A30 ~/movie-srt [1]# python main.py                                                                                                                                                 (funasr-rst)
2024-03-07 10:31:28,738 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-03-07 10:31:28,738 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-03-07 10:31:28,765 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 15928bc22e3de68c7bf1a1e5c99158aa and a total number of 964 components indexed
2024-03-07 10:31:30,010 - modelscope - WARNING - Model revision not specified, use revision: v2.0.4
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 76.3kB/s]
2024-03-07 10:31:30,531 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020
2024-03-07 10:31:30,531 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020.
2024-03-07 10:31:30,532 - modelscope - INFO - initialize model from /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020
If you want to use hugging, please `pip install -U transformers`
ckpt: /root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020/model.pt
2024-03-07 10:31:36,438 - modelscope - WARNING - Model revision not specified, use revision: v2.0.4
ckpt: /root/.cache/modelscope/hub/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt
2024-03-07 10:31:37,026 - modelscope - WARNING - Model revision not specified, use revision: v2.0.4
ckpt: /root/.cache/modelscope/hub/iic/punc_ct-transformer_cn-en-common-vocab471067-large/model.pt
2024-03-07 10:31:43,247 - modelscope - WARNING - Model revision not specified, use revision: v2.0.2
ckpt: /root/.cache/modelscope/hub/iic/speech_campplus_sv_zh-cn_16k-common/campplus_cn_common.bin
2024-03-07 10:31:43,717 - modelscope - WARNING - No preprocessor field found in cfg.
2024-03-07 10:31:43,717 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-03-07 10:31:43,717 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/root/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020'}. trying to build by task and model information.
2024-03-07 10:31:43,717 - modelscope - WARNING - No preprocessor key ('funasr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
rtf_avg: 0.581: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:16<00:00, 16.64s/it]
  0%|                                                                                                                                                                            | 0/1 [00:00<?, ?it/sTraceback (most recent call last):                                                                                                                                              | 0/247 [00:00<?, ?it/s]
  File "main.py", line 10, in <module>
    inference_pipeline(input="./myhb.wav")
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/pipelines/audio/funasr_pipeline.py", line 73, in __call__
    output = self.model(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/models/base/base_model.py", line 35, in __call__
    return self.postprocess(self.forward(*args, **kwargs))
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/modelscope/models/audio/funasr/model.py", line 61, in forward
    output = self.model.generate(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/auto/auto_model.py", line 215, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/auto/auto_model.py", line 338, in inference_with_vad
    results = self.inference(speech_j, input_len=None, model=model, kwargs=kwargs, **cfg)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/auto/auto_model.py", line 248, in inference
    res = model.inference(**batch, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/models/paraformer/model.py", line 481, in inference
    predictor_outs = self.calc_predictor(encoder_out, encoder_out_lens)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/models/paraformer/model.py", line 272, in calc_predictor
    pre_acoustic_embeds, pre_token_length, alphas, pre_peak_index = self.predictor(encoder_out, None,
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/funasr/models/paraformer/cif_predictor.py", line 179, in forward
    output = torch.relu(self.cif_conv1d(queries))
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/funasr-rst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Invalid argument
  0%|                                                                                                                                                                          | 0/247 [00:02<?, ?it/s]
  0%|                                                                                                                                          
`

### Environment

 - OS (e.g., Linux): Linux
 - FunASR Version (e.g., 1.0.0): 1.0.14
 - ModelScope Version (e.g., 1.11.0): 1.12.0
 - PyTorch Version (e.g., 2.0.0):  2.2.1
 - How you installed funasr (`pip`, source):  pip
 - Python version: 3.8
 - GPU (e.g., V100M32) A30
 - CUDA/cuDNN version (e.g., cuda11.7): 12.2

**Comment by LauraGPT** [comment]
Doc has been updated, please try it again: https://www.modelscope.cn/models/iic/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020/summary
