### ISSUE TITLE
load onnx时报错

### ISSUE THREAD

**Issue by LRY1994** [alibaba-damo-academy/FunASR#1466]
model_path="dengcunqin/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online"
model = AutoModel(model=model_path,                               
                  device='cpu')
res = model.export(type="onnx", quantize=False)
  

 from funasr_onnx.paraformer_online_bin import Paraformer
 model = Paraformer(model_path, 
                batch_size=1, 
                quantize=False, 
                chunk_size=chunk_size, 
                intra_op_num_threads=4,
                ) # only support batch_size = 1

```
Traceback (most recent call last):
  File "/data/linry/FunASR/my.py", line 43, in main
    model = Paraformer(model_path, 
  File "/data/linry/FunASR/runtime/python/onnxruntime/funasr_onnx/paraformer_online_bin.py", line 75, in __init__
    self.ort_encoder_infer = OrtInferSession(encoder_model_file, device_id,
  File "/data/linry/FunASR/runtime/python/onnxruntime/funasr_onnx/utils/utils.py", line 208, in __init__
    self.session = InferenceSession(model_file,
  File "/data/linry/anaconda3/envs/funasr-new/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/data/linry/anaconda3/envs/funasr-new/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /data/linry/cantonese-paraformer/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online/model.onnx failed:Type Error: Type parameter (Tind) of Optype (Slice) bound to different types (tensor(int64) and tensor(int32) in node (/make_pad_mask/Slice).
```

**Comment by LauraGPT** [comment]
Bug has been fixed. Please update funasr by source code and try it again.

**Comment by acetotot** [comment]
> Bug has been fixed. Please update funasr by source code and try it again.

raise new question：
Traceback (most recent call last):
  File "/data/project_lzl/asr/1.py", line 58, in <module>
    model = Paraformer(model_dir, batch_size=1, quantize=False)
  File "/data/project_lzl/anaconda3/envs/asr/lib/python3.8/site-packages/funasr_onnx/paraformer_bin.py", line 76, in __init__
    self.converter = TokenIDConverter(config['token_list'])
KeyError: 'token_list'

**Comment by bigchou** [comment]
Traceback (most recent call last):
  File "/data/FunASR/test_onnx.py", line 6, in <module>
    model = Paraformer(model_dir, batch_size=1, quantize=True)
  File "/data/miniconda3/envs/funasr/lib/python3.10/site-packages/funasr_onnx/paraformer_bin.py", line 76, in __init__
    self.converter = TokenIDConverter(config['token_list'])
KeyError: 'token_list'

funasr.__version__ == '1.0.15'
modelscope.__version__ == '1.13.0'

**Comment by LauraGPT** [comment]
Bug has been fixed, please update funasr and try it again. https://github.com/alibaba-damo-academy/FunASR/commit/c3192dffdd79c7b8a75ce1dc880b0a17b72d33a1#diff-109936cebd2ecde16995eb96e9d3318d72163882799766446363edb4e2218add

**Comment by LauraGPT** [comment]
Bug has been fixed, please update funasr and try it again.
