### ISSUE TITLE
用finetune.sh微调paraformer_streaming模型报错

### ISSUE THREAD

**Issue by dospeech** [alibaba-damo-academy/FunASR#1478]
问题描述：
用finetune.sh微调paraformer_streaming模型（下载的speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online模型，模型路径也可以找到）报错如下，一直没跑上，请问是哪里的问题：

[2024-03-12 06:40:34,414][root][INFO] - init_param is not None: ('/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt',)
[2024-03-12 06:40:34,414][root][INFO] - Loading pretrained params from /workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt
ckpt: /workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt
[2024-03-12 06:40:34,421][root][INFO] - init_param is not None: ('/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt',)
[2024-03-12 06:40:34,422][root][INFO] - Loading pretrained params from /workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt
[2024-03-12 06:40:34,426][root][INFO] - init_param is not None: ('/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt',)
[2024-03-12 06:40:34,426][root][INFO] - Loading pretrained params from /workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt
ckpt: /workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt
ckpt: /workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt
[2024-03-12 06:40:49,798][root][INFO] - total_num of samplers across ranks: 2042300
[2024-03-12 06:40:49,800][root][INFO] - total_num of samplers across ranks: 2042300
[2024-03-12 06:40:49,803][root][INFO] - total_num of samplers across ranks: 2042300
[2024-03-12 06:40:49,809][root][INFO] - total_num of samplers across ranks: 2042300
[2024-03-12 06:40:49,819][root][INFO] - total_num of samplers across ranks: 2042300
[2024-03-12 06:40:49,821][root][INFO] - total_num of samplers across ranks: 2042300
[2024-03-12 06:40:49,829][root][INFO] - total_num of samplers across ranks: 5281
[2024-03-12 06:40:49,829][root][INFO] - total_num of samplers across ranks: 5281
[2024-03-12 06:40:49,833][root][INFO] - total_num of samplers across ranks: 5281
[2024-03-12 06:40:49,835][root][INFO] - total_num of samplers across ranks: 2042300
[2024-03-12 06:40:49,838][root][INFO] - total_num of samplers across ranks: 5281
No checkpoint found at './outputs/model.pt', starting from scratch
No checkpoint found at './outputs/model.pt', starting from scratch
No checkpoint found at './outputs/model.pt', starting from scratch
No checkpoint found at './outputs/model.pt', starting from scratch
[2024-03-12 06:40:49,848][root][INFO] - total_num of samplers across ranks: 5281
[2024-03-12 06:40:49,850][root][INFO] - total_num of samplers across ranks: 5281
[2024-03-12 06:40:49,851][root][INFO] - total_num of samplers across ranks: 2042300
No checkpoint found at './outputs/model.pt', starting from scratch
No checkpoint found at './outputs/model.pt', starting from scratch
[2024-03-12 06:40:49,865][root][INFO] - total_num of samplers across ranks: 5281
No checkpoint found at './outputs/model.pt', starting from scratch
[2024-03-12 06:40:49,881][root][INFO] - total_num of samplers across ranks: 5281
No checkpoint found at './outputs/model.pt', starting from scratch
rank: 0, Training Epoch: 1:   0%|          | 0/63822 [00:00<?, ?it/s]Error executing job with overrides: ['++train_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/train.jsonl', '++valid_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/val.jsonl', '++tokenizer_conf.token_list=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/tokens.json', '++frontend_conf.cmvn_file=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/am.mvn', '++dataset_conf.batch_size=32', '++dataset_conf.batch_type=example', '++dataset_conf.num_workers=4', '++train_conf.max_epoch=20', '++optim_conf.lr=0.0002', '++train_conf.log_interval=1', '++init_param=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt', '++output_dir=./outputs']
Error executing job with overrides: ['++train_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/train.jsonl', '++valid_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/val.jsonl', '++tokenizer_conf.token_list=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/tokens.json', '++frontend_conf.cmvn_file=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/am.mvn', '++dataset_conf.batch_size=32', '++dataset_conf.batch_type=example', '++dataset_conf.num_workers=4', '++train_conf.max_epoch=20', '++optim_conf.lr=0.0002', '++train_conf.log_interval=1', '++init_param=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt', '++output_dir=./outputs']
Error executing job with overrides: ['++train_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/train.jsonl', '++valid_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/val.jsonl', '++tokenizer_conf.token_list=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/tokens.json', '++frontend_conf.cmvn_file=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/am.mvn', '++dataset_conf.batch_size=32', '++dataset_conf.batch_type=example', '++dataset_conf.num_workers=4', '++train_conf.max_epoch=20', '++optim_conf.lr=0.0002', '++train_conf.log_interval=1', '++init_param=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt', '++output_dir=./outputs']
Error executing job with overrides: ['++train_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/train.jsonl', '++valid_data_set_list=/workspace/install_dir/root_conda_wenet/wenet/examples/aishell2/8k_16k/data/dataV0.1_opendata/funasr_changjing_dir/val.jsonl', '++tokenizer_conf.token_list=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/tokens.json', '++frontend_conf.cmvn_file=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/am.mvn', '++dataset_conf.batch_size=32', '++dataset_conf.batch_type=example', '++dataset_conf.num_workers=4', '++train_conf.max_epoch=20', '++optim_conf.lr=0.0002', '++train_conf.log_interval=1', '++init_param=/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt', '++output_dir=./outputs']
Traceback (most recent call last):
  File "../../../funasr/bin/train.py", line 42, in main_hydra
    main(**kwargs)
  File "../../../funasr/bin/train.py", line 192, in main
    trainer.run()
  File "/workspace/49_funasr/FunASR/funasr/train_utils/trainer.py", line 181, in run
    self._train_epoch(epoch)
  File "/workspace/49_funasr/FunASR/funasr/train_utils/trainer.py", line 245, in _train_epoch
    retval = self.model(**batch)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/49_funasr/FunASR/funasr/models/paraformer_streaming/model.py", line 120, in forward
    loss_att, acc_att, cer_att, wer_att, loss_pre, pre_loss_att = self._calc_att_predictor_loss(
  File "/workspace/49_funasr/FunASR/funasr/models/paraformer_streaming/model.py", line 259, in _calc_att_predictor_loss
    loss_att = self.criterion_att(decoder_out, ys_pad)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/49_funasr/FunASR/funasr/losses/label_smoothing_loss.py", line 51, in forward
    assert x.size(2) == self.size
AssertionError

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**finetune里面的微调主要代码如下：**

torchrun \
--nnodes 1 \
--nproc_per_node ${gpu_num} \
../../../funasr/bin/train.py \
++model="/workspace/49_funasr/FunASR/examples/industrial_data_pretraining/paraformer_streaming/exp/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online" \
++model_revision="v2.0.4" \
++train_data_set_list="${train_data}" \
++valid_data_set_list="${val_data}" \
++dataset_conf.batch_size=32 \
++dataset_conf.batch_type="example" \
++dataset_conf.num_workers=4 \
++train_conf.max_epoch=20 \
++optim_conf.lr=0.0002 \
++output_dir="${output_dir}" &> ${log_file}

#### What's your environment?

 - OS (e.g., Linux):Debian GNU/Linux 10 
 - FunASR Version (e.g., 1.0.0):1.0.0
 - ModelScope Version (e.g., 1.11.0):v2.04
 - PyTorch Version (e.g., 2.0.0):1.13.0+cu117
 - How you installed funasr (`pip`, source): source
 - Python version: v3.8
 - GPU (e.g., V100M32)：v100M32

**Comment by LauraGPT** [comment]
Please update funasr and try it again.

**Comment by dospeech** [comment]
> Please update funasr and try it again.

Thanks. I'll try it right away

**Comment by LRY1994** [comment]
the same

**Comment by QDPeng** [comment]
same error for me,  assert x.size(2) == self.size .     x.size(2) is 320, self.size is 8404

**Comment by NLPvv** [comment]
我也遇到了同样的问题
![image](https://github.com/alibaba-damo-academy/FunASR/assets/99643269/387be9ff-431e-4efb-9c4c-ac9ae1cf5c07)

**离线的模型finetune是正常的**

**Comment by LauraGPT** [comment]
Bug has been fixed. Please update funasr and try it again. The demo is : https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/paraformer_streaming/finetune.sh

**Comment by dospeech** [comment]
> Bug has been fixed. Please update funasr and try it again. The demo is : https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/paraformer_streaming/finetune.sh

Thanks for your work

**Comment by NLPvv** [comment]
**I try test,no problem**

| training log  and GPU memory |
| ----------------------------------|  
| ![image](https://github.com/alibaba-damo-academy/FunASR/assets/99643269/fcf9279a-0b0c-44c2-948e-f6d0723999af) |
 
@LauraGPT  Thanks

**Comment by LRY1994** [comment]
model_name_or_model_dir="iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online"
model_revision="master"

**Comment by LRY1994** [comment]
model_name_or_model_dir="iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online"
model_revision="master"
这个模型还是有这个问题

**Comment by LRY1994** [comment]
model_name_or_model_dir="dengcunqin/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online"
model_revision="master"

我已经git pull更新了，还是出现这个错误

    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/data/linry/anaconda3/envs/asr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/linry/FunASR/funasr/models/paraformer_streaming/model.py", line 120, in forward
    loss_att, acc_att, cer_att, wer_att, loss_pre, pre_loss_att = self._calc_att_predictor_loss(
  File "/data/linry/FunASR/funasr/models/paraformer_streaming/model.py", line 259, in _calc_att_predictor_loss
    loss_att = self.criterion_att(decoder_out, ys_pad)
  File "/data/linry/anaconda3/envs/asr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/linry/FunASR/funasr/losses/label_smoothing_loss.py", line 51, in forward
    assert x.size(2) == self.size
AssertionError


x.size(2) is 512, self.size is 8501
