### ISSUE TITLE
onnx model check error because  Nodes in a graph not be topologically sorted

### ISSUE THREAD

**Issue by soulseen** [alibaba-damo-academy/FunASR#1566]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug
model：https://modelscope.cn/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx/files
use onnx checker to check model, but get error： 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.conda/lib/python3.11/site-packages/onnx/checker.py", line 137, in check_model
    C.check_model_path(os.fspath(model), full_check, skip_opset_compatibility_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '/predictor/Add_output_0' of node: 
name: Gather_6387 OpType: Gather
 is not output of any previous nodes.

==> Context: Bad node spec for node. Name: Loop_6386 OpType: Loop
```

### To Reproduce

1. download model from https://modelscope.cn/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx/file/view/master/model_quant.onnx?status=2
2. check model:
```
import onnx
onnx.checker.check_model("/models/funasr/model_quant.onnx")
```
3. get error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/.conda/lib/python3.11/site-packages/onnx/checker.py", line 137, in check_model
    C.check_model_path(os.fspath(model), full_check, skip_opset_compatibility_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '/predictor/Add_output_0' of node: 
name: Gather_6387 OpType: Gather
 is not output of any previous nodes.

==> Context: Bad node spec for node. Name: Loop_6386 OpType: Loop
```

**Comment by LauraGPT** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/README_zh.md#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E6%B5%8B%E8%AF%95
