### ISSUE TITLE
使用 funasr 管道和 websocket python-api 的演示的报错：TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Jacoo520** [alibaba-damo-academy/FunASR#1578]
我是从这里下载的FunASR源码：[](https://github.com/alibaba-damo-academy/FunASR/tree/dev_lyb)

> 现在正在使用 funasr 管道和 websocket python-api 的演示这一步，使用默认的参数没有问题，我现在想从modelscope模型库里加载韩语、日语、越南语进行麦克风实时语音识别，日语运行是没有问题的，目前是韩语和越南语都报同样的报错，想知道funasr_wss_server.py里面的参数换模型我是否有操作错误。

- funasr_wss_server.py文件的参数设置，日语成功运行参数设置：
- 在WSL运行命令：`python funasr_wss_server.py --port 10095`

```
parser.add_argument("--host",
                    type=str,
                    default="0.0.0.0",
                    required=False,
                    help="host ip, localhost, 0.0.0.0")
parser.add_argument("--port",
                    type=int,
                    default=10095,
                    required=False,
                    help="grpc server port")
parser.add_argument("--asr_model",
                    type=str,
                    default="iic/speech_UniASR_asr_2pass-ja-16k-common-vocab93-tensorflow1-offline",
                    help="model from modelscope")
parser.add_argument("--asr_model_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--asr_model_online",
                    type=str,
                    default="iic/speech_UniASR_asr_2pass-ja-16k-common-vocab93-tensorflow1-online",
                    help="model from modelscope")
parser.add_argument("--asr_model_online_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--vad_model",
                    type=str,
                    default="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                    help="model from modelscope")
parser.add_argument("--vad_model_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--punc_model",
                    type=str,
                    default="iic/punc_ct-transformer_cn-en-common-vocab471067-large",
                    help="model from modelscope")
parser.add_argument("--punc_model_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--ngpu",
                    type=int,
                    default=1,
                    help="0 for cpu, 1 for gpu")
parser.add_argument("--device",
                    type=str,
                    default="cuda",
                    help="cuda, cpu")
parser.add_argument("--ncpu",
                    type=int,
                    default=4,
                    help="cpu cores")
parser.add_argument("--certfile",
                    type=str,
                    default="../../ssl_key/server.crt",
                    required=False,
                    help="certfile for ssl")

parser.add_argument("--keyfile",
                    type=str,
                    default="../../ssl_key/server.key",
                    required=False,
                    help="keyfile for ssl")
```

- funasr_wss_server.py文件的参数设置，韩语失败运行参数设置：

```
parser.add_argument("--host",
                    type=str,
                    default="0.0.0.0",
                    required=False,
                    help="host ip, localhost, 0.0.0.0")
parser.add_argument("--port",
                    type=int,
                    default=10095,
                    required=False,
                    help="grpc server port")
parser.add_argument("--asr_model",
                    type=str,
                    default="iic/speech_UniASR_asr_2pass-ko-16k-common-vocab6400-tensorflow1-offline",
                    help="model from modelscope")
parser.add_argument("--asr_model_revision",
                    type=str,
                    default="v1.0.1",
                    help="")
parser.add_argument("--asr_model_online",
                    type=str,
                    default="iic/speech_UniASR_asr_2pass-ko-16k-common-vocab6400-tensorflow1-online",
                    help="model from modelscope")
parser.add_argument("--asr_model_online_revision",
                    type=str,
                    default="v1.0.1",
                    help="")
parser.add_argument("--vad_model",
                    type=str,
                    default="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                    help="model from modelscope")
parser.add_argument("--vad_model_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--punc_model",
                    type=str,
                    default="iic/punc_ct-transformer_cn-en-common-vocab471067-large",
                    help="model from modelscope")
parser.add_argument("--punc_model_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--ngpu",
                    type=int,
                    default=1,
                    help="0 for cpu, 1 for gpu")
parser.add_argument("--device",
                    type=str,
                    default="cuda",
                    help="cuda, cpu")
parser.add_argument("--ncpu",
                    type=int,
                    default=4,
                    help="cpu cores")
parser.add_argument("--certfile",
                    type=str,
                    default="../../ssl_key/server.crt",
                    required=False,
                    help="certfile for ssl")

parser.add_argument("--keyfile",
                    type=str,
                    default="../../ssl_key/server.key",
                    required=False,
                    help="keyfile for ssl")
```

- 韩语模型运行报错日志：

```
(FunASR38) jacoo@Jacoo:~/FunASR/runtime/python/websocket$ python funasr_wss_server.py --port 10095
model loading
2024-04-01 15:46:13,951 - modelscope - INFO - PyTorch version 2.2.2+cu118 Found.
2024-04-01 15:46:13,951 - modelscope - INFO - Loading ast index from /home/jacoo/.cache/modelscope/ast_indexer
2024-04-01 15:46:13,969 - modelscope - INFO - Loading done! Current index file version is 1.13.3, with md5 48db5a2a0bc1807a7f786037717f9db5 and a total number of 972 components indexed
2024-04-01 15:46:14,389 - modelscope - INFO - Use user-specified model revision: v1.0.1
Downloading: 100%|█████████████████████████████████████████████████████████████| 456/456 [00:00<00:00, 65.3kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████| 391M/391M [03:00<00:00, 2.27MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████| 23.5k/23.5k [00:00<00:00, 395kB/s]
Traceback (most recent call last):
  File "funasr_wss_server.py", line 87, in <module>
    model_asr = AutoModel(model=args.asr_model,
  File "/home/jacoo/FunASR/funasr/auto/auto_model.py", line 104, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/home/jacoo/FunASR/funasr/auto/auto_model.py", line 185, in build_model
    model = model_class(**kwargs, **kwargs.get("model_conf", {}), vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable
```
- funasr_wss_server.py文件的参数设置，越南失败运行参数设置：
```
parser.add_argument("--host",
                    type=str,
                    default="0.0.0.0",
                    required=False,
                    help="host ip, localhost, 0.0.0.0")
parser.add_argument("--port",
                    type=int,
                    default=10095,
                    required=False,
                    help="grpc server port")
parser.add_argument("--asr_model",
                    type=str,
                    default="iic/speech_UniASR_asr_2pass-vi-16k-common-vocab1001-pytorch-offline",
                    help="model from modelscope")
parser.add_argument("--asr_model_revision",
                    type=str,
                    default="v1.0.0",
                    help="")
parser.add_argument("--asr_model_online",
                    type=str,
                    default="iic/speech_UniASR_asr_2pass-vi-16k-common-vocab1001-pytorch-online",
                    help="model from modelscope")
parser.add_argument("--asr_model_online_revision",
                    type=str,
                    default="v1.0.0",
                    help="")
parser.add_argument("--vad_model",
                    type=str,
                    default="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                    help="model from modelscope")
parser.add_argument("--vad_model_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--punc_model",
                    type=str,
                    default="iic/punc_ct-transformer_cn-en-common-vocab471067-large",
                    help="model from modelscope")
parser.add_argument("--punc_model_revision",
                    type=str,
                    default="v2.0.4",
                    help="")
parser.add_argument("--ngpu",
                    type=int,
                    default=1,
                    help="0 for cpu, 1 for gpu")
parser.add_argument("--device",
                    type=str,
                    default="cuda",
                    help="cuda, cpu")
parser.add_argument("--ncpu",
                    type=int,
                    default=4,
                    help="cpu cores")
parser.add_argument("--certfile",
                    type=str,
                    default="../../ssl_key/server.crt",
                    required=False,
                    help="certfile for ssl")

parser.add_argument("--keyfile",
                    type=str,
                    default="../../ssl_key/server.key",
                    required=False,
                    help="keyfile for ssl")
```

- 越南语模型运行报错日志：

```
(FunASR38) jacoo@Jacoo:~/FunASR/runtime/python/websocket$ python funasr_wss_server.py --port 10095
model loading
2024-04-01 15:52:56,759 - modelscope - INFO - PyTorch version 2.2.2+cu118 Found.
2024-04-01 15:52:56,760 - modelscope - INFO - Loading ast index from /home/jacoo/.cache/modelscope/ast_indexer
2024-04-01 15:52:56,776 - modelscope - INFO - Loading done! Current index file version is 1.13.3, with md5 48db5a2a0bc1807a7f786037717f9db5 and a total number of 972 components indexed
2024-04-01 15:52:57,193 - modelscope - INFO - Use user-specified model revision: v1.0.0
Traceback (most recent call last):
  File "funasr_wss_server.py", line 87, in <module>
    model_asr = AutoModel(model=args.asr_model,
  File "/home/jacoo/FunASR/funasr/auto/auto_model.py", line 104, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/home/jacoo/FunASR/funasr/auto/auto_model.py", line 185, in build_model
    model = model_class(**kwargs, **kwargs.get("model_conf", {}), vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable
```

> 适用于linux的widows子系统
> ubuntu：20.04.6LTS
> modelscope:1.13.3
> pytorch:2.2.2+cu118

我是小白，可能有些信息给的不全面，希望可以有高人指点！

**Comment by LauraGPT** [comment]
UniASR model could not been used as online model.

**Comment by Jacoo520** [comment]
> UniASR模型不能用作在线模型。

那为什么日语的就可以呢？
