### ISSUE TITLE
使用本地预训练模型进行推理报错

### ISSUE THREAD

**Issue by 16lkj** [alibaba-damo-academy/FunASR#1621]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
使用本地预训练模型进行推理报错。Download: ./iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt failed!:

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
我先使用范例代码，能正常推理，然后去模型的相应文件夹将模型文件夹复制到代码文件夹下，希望将路径换成本地路径进行推理。
![image](https://github.com/alibaba-damo-academy/FunASR/assets/132660841/6d2dae4a-2bd7-4456-8c0a-a35b8fb0bfed)
结果报错。
2024-04-17 09:48:21,184 - modelscope - ERROR - Authentication token does not exist, failed to access model ./iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt which may not exist or may be                 private. Please login first.
Download: ./iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt failed!: Response details: 404 page not found, Request id: 0d4acdd5098a4706abb4b7feb77eae83
Traceback (most recent call last):
  File "c:/Users/PC/Desktop/hello/asr_test2.py", line 13, in <module>
    model = AutoModel(
  File "C:\Users\PC\AppData\Local\conda\conda\envs\modelscope\lib\site-packages\funasr\auto\auto_model.py", line 106, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "C:\Users\PC\AppData\Local\conda\conda\envs\modelscope\lib\site-packages\funasr\auto\auto_model.py", line 194, in build_model
    model = model_class(**model_conf, vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable
![image](https://github.com/alibaba-damo-academy/FunASR/assets/132660841/8841d7b7-93e2-4e47-8c27-bbe6a652167d)
#### Code

![image](https://github.com/alibaba-damo-academy/FunASR/assets/132660841/ff008df5-3100-4c06-8477-0db6838062f5)
#### What's your environment?
python==3.8 + funasr==1.0.23 + modelscope==1.11.1
 - OS (e.g., Linux):   windows
 - FunASR Version (e.g., 1.0.0):  1.0.23
 - ModelScope Version (e.g., 1.11.0):  1.11.1
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):  pip
 - Python version:  3.8
 - GPU (e.g., V100M32)  CPU
 - CUDA/cuDNN version (e.g., cuda11.7): None
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by zkf12** [comment]
怎么解决的
