### ISSUE TITLE
你好，在微调的时候，用默认的数据集，执行bash finetune.sh ，有一个报错，麻烦帮忙看一下

### ISSUE THREAD

**Issue by hn529945497** [alibaba-damo-academy/FunASR#1692]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

#### What is your question?
[rank0]: Traceback (most recent call last):
[rank0]:   File "../../../funasr/bin/train.py", line 251, in <module>
[rank0]:     main_hydra()
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
[rank0]:     _run_hydra(
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
[rank0]:     _run_app(
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
[rank0]:     run_and_report(
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
[rank0]:     raise ex
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
[rank0]:     return func()
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
[rank0]:     lambda: hydra.run(
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
[rank0]:     _ = ret.return_value
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
[rank0]:     raise self._return_value
[rank0]:   File "/root/miniconda/envs/funasr_/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
[rank0]:     ret.return_value = task_function(task_cfg)
[rank0]:   File "../../../funasr/bin/train.py", line 51, in main_hydra
[rank0]:     main(**kwargs)
[rank0]:   File "../../../funasr/bin/train.py", line 204, in main
[rank0]:     for data_split_i in range(trainer.start_data_split_i, dataloader.data_split_num):
[rank0]: AttributeError: 'Trainer' object has no attribute 'start_data_split_i'

执行bash finetune.sh，报错信息是这个，生成不了微调后的模型文件，

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
There exists `start_data_split_i ` in https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/train_utils/trainer.py#L117

Please update funasr and re-install it: `pip install -e ./`
