### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by kexul** [alibaba-damo-academy/FunASR#1711]
## 🐛 Bug
The Cantonese model raised the following error:
    model = AutoModel(model='iic/speech_UniASR_asr_2pass-cantonese-CHS-16k-common-vocab1468-tensorflow1-offline')#, model_revision="v1.0.1")
  File "/home/user/miniconda/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 117, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/home/user/miniconda/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 213, in build_model
    model = model_class(**model_conf, vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable

### To Reproduce

```python
from funasr import AutoModel

model = AutoModel(model='iic/speech_UniASR_asr_2pass-cantonese-CHS-16k-common-vocab1468-tensorflow1-offline')#, model_revision="v1.0.1")

res = model.generate(input="/data/tts/sovits/audio_res/e1/11_2.wav")
print(res)
```

### Environment

 - OS (e.g., Linux): Linux 
 - FunASR Version (e.g., 1.0.0): 1.0.26
 - ModelScope Version (e.g., 1.11.0): 1.14.0
 - PyTorch Version (e.g., 2.0.0): 2.1.2
 - How you installed funasr (`pip`, source): pip 
 - Python version: 3.9.13
 - GPU (e.g., V100M32) RTX4090

**Comment by kexul** [comment]
It seems like the 'iic/speech_UniASR_asr_2pass-cantonese-CHS-16k-common-vocab1468-tensorflow1-online` is usable. 

I checked the code of `auto_model.py`, it seem like the model config.yaml need to be updated so that it could be used in the AutoModel class. 

For anyone else who encountered this problem, please check your model files'  `config.yaml`.

**Comment by hgqimo** [comment]
> Author

请问 config.yaml 具体要怎么改呢

**Comment by kexul** [comment]
> > Author
> 
> 请问 config.yaml 具体要怎么改呢

如果不清楚具体的模型架构的话估计不好改，而且这玩意还得配合funasr的。
所以建议是尽量用近期有过更新的模型。去模型的文件里面可以看到更新记录。
如果实在找不到的话，就去找找看看类似的模型有没有更新过的，然后从参考那个改也许能行。

**Comment by LLH-Harward** [comment]
在使用examples/industrial_data_pretraining/whisper/demo.py的时候我也碰到了同样的问题
Traceback (most recent call last):
  File "D:\Yi-main\FunASR-main\openai_whisper_infer.py", line 10, in <module>
    model = AutoModel(
  File "D:\Yi-main\FunASR-main\funasr\auto\auto_model.py", line 118, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "D:\Yi-main\FunASR-main\funasr\auto\auto_model.py", line 214, in build_model
    model = model_class(**model_conf, vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable

code:
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
# Copyright FunASR (https://github.com/alibaba-damo-academy/FunASR). All Rights Reserved.
#  MIT License  (https://opensource.org/licenses/MIT)

# To install requirements: pip3 install -U openai-whisper

from funasr import AutoModel

model = AutoModel(
    model="iic/Whisper-large-v3",
    vad_model="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
    vad_kwargs={"max_single_segment_time": 30000},
)

DecodingOptions = {
    "task": "transcribe",
    "language": None,
    "beam_size": None,
    "fp16": True,
    "without_timestamps": False,
    "prompt": None,
}
res = model.generate(
    DecodingOptions=DecodingOptions,
    batch_size_s=0,
    input="https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav",
)

print(res)
