### ISSUE TITLE
finetune训练时，内存会随着训练步数增多而增大，直到占满内存报错 Cannot allocate memory 

### ISSUE THREAD

**Issue by JucyCherry** [alibaba-damo-academy/FunASR#1716]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

[rank2]: OSError: [Errno 12] Cannot allocate memory 

### To Reproduce

examples/industrial_data_pretraining/paraformer/finetune.sh

### Additional context

finetune训练时，内存会随着训练步数增多而增大，又可能是哪里的内存占用后没有释放吗

**Comment by lixikun** [comment]
我使用 examples/industrial_data_pretraining/seaco_paraformer/finetune.sh 脚本进行微调，调了几次batch_size,最后都会在这个位置报错，
  
硬件为：40G的A100

微调的参数为：

```
torchrun \
--nnodes 1 \
--nproc_per_node ${gpu_num} \
/opt/conda/lib/python3.10/site-packages/funasr/bin/train.py \
++model="${model_name_or_model_dir}" \
++train_data_set_list="${train_data}" \
++valid_data_set_list="${val_data}" \
++dataset_conf.batch_size=2400 \
++dataset_conf.batch_type="token" \
++dataset_conf.num_workers=1 \
++train_conf.max_epoch=50 \
++train_conf.log_interval=1 \
++train_conf.resume=false \
++train_conf.validate_interval=2000 \
++train_conf.save_checkpoint_interval=2000 \
++train_conf.avg_keep_nbest_models_type='loss' \
++train_conf.keep_nbest_models=10 \
++optim_conf.lr=0.0002 \
++output_dir="${output_dir}" &> ${log_file}
```

```
- train, rank: 0, epoch: 0/50, data_slice: 0/1, step_in_slice: 81148/1, step_in_epoch: 81148, total step: 81148, (loss_avg_rank: 0.332), (loss_avg_epoch: 0.317), (ppl_avg_epoch: 1.373e+00), (acc_avg_epoch: 0.000), (lr: 2.432e-05), [('loss_att', 0.659), ('acc_att', 0.579), ('loss_seaco', 0.326), ('loss', 0.332)], {'data_load': '0.001', 'forward_time': '0.350', 'backward_time': '0.386', 'optim_time': '0.069', 'total_time': '0.815'}, GPU, memory: usage: 2.826 GB, peak: 35.274 GB, cache: 38.080 GB, cache_peak: 38.775 GB
Error executing job with overrides: ['++model=iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', '++train_data_set_list=train_data/train.jsonl', '++valid_data_set_list=train_data/val.jsonl', '++dataset_conf.batch_size=2400', '++dataset_conf.batch_type=token', '++dataset_conf.num_workers=1', '++train_conf.max_epoch=50', '++train_conf.log_interval=1', '++train_conf.resume=false', '++train_conf.validate_interval=2000', '++train_conf.save_checkpoint_interval=2000', '++train_conf.avg_keep_nbest_models_type=loss', '++train_conf.keep_nbest_models=10', '++optim_conf.lr=0.00004', '++output_dir=./outputs']
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/funasr/bin/train.py", line 251, in <module>
    main_hydra()
  File "/opt/conda/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/conda/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/conda/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/opt/conda/lib/python3.10/site-packages/funasr/bin/train.py", line 51, in main_hydra
    main(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/funasr/bin/train.py", line 209, in main
    trainer.train_epoch(
 File "/opt/conda/lib/python3.10/site-packages/funasr/train_utils/trainer.py", line 377, in train_epoch
    retval = model(**batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/funasr/models/seaco_paraformer/model.py", line 150, in forward
    loss_seaco = self._calc_seaco_loss(
  File "/opt/conda/lib/python3.10/site-packages/funasr/models/seaco_paraformer/model.py", line 208, in _calc_seaco_loss
    decoder_out, _ = self.decoder(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/funasr/models/paraformer/decoder.py", line 397, in forward
    x, tgt_mask, memory, memory_mask, _ = self.decoders(x, tgt_mask, memory, memory_mask)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/funasr/models/transformer/utils/repeat.py", line 32, in forward
    args = m(*args)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/funasr/models/paraformer/decoder.py", line 117, in forward
    x_src_attn = self.src_attn(x, memory, memory_mask, ret_attn=False)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/funasr/models/sanm/attention.py", line 711, in forward
    return self.forward_attention(v_h, scores, memory_mask, ret_attn=ret_attn)
  File "/opt/conda/lib/python3.10/site-packages/funasr/models/sanm/attention.py", line 680, in forward_attention
    self.attn = torch.softmax(scores, dim=-1).masked_fill(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB. GPU 0 has a total capacty of 39.39 GiB of which 12.88 MiB is free. Process 32650 has 39.37 GiB memory in use. Of the allocated memory 37.07 GiB is allocated by PyTorch, and 1.77 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-05-12 09:06:56,919] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 5636) of binary: /opt/conda/bin/python
```

**Comment by OvO616** [comment]
我也遇到了这个问题 有解决吗

**Comment by wangchao112211** [comment]
请问这个解决了吗？我也遇到了
