### ISSUE TITLE
grpc_main_client_mic.py 文件修改mic_chunk 参数报错

### ISSUE THREAD

**Issue by zhiyongLiu1114** [alibaba-damo-academy/FunASR#173]
报错信息：
* recording
Traceback (most recent call last):
  File "grpc_main_client_mic.py", line 136, in <module>
    asyncio.run(record(args.host,args.port,args.sample_rate,args.mic_chunk,args.record_seconds,args.user_allowed,language))
  File "/Users/liuzhiyong/anaconda3/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/liuzhiyong/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "grpc_main_client_mic.py", line 72, in record
    await asyncio.create_task(deal_chunk(sig_mic))
  File "grpc_main_client_mic.py", line 45, in deal_chunk
    if vad.is_speech(sig_mic, sample_rate): #speaking
  File "/Users/liuzhiyong/anaconda3/lib/python3.7/site-packages/webrtcvad.py", line 27, in is_speech
    return _webrtcvad.process(self._vad, sample_rate, buf, length)
webrtcvad.Error: Error while processing frame

**Comment by dyyzhmm** [comment]
So, you make changes on mic_chunk ?   
In default , mic_chunk is 160 frames means 10ms for sample rate 16kHZ.
And webrtcvad support only 10ms 20ms 30ms chunk.
So, what's your mic_chunk value ?

**Comment by zhiyongLiu1114** [comment]
> So, you make changes on mic_chunk ? In default , mic_chunk is 160 frames means 10ms for sample rate 16kHZ. And webrtcvad support only 10ms 20ms 30ms chunk. So, what's your mic_chunk value ?

了解了，谢谢，我设置了1600等其他参数，没有满足10ms 20ms 30ms，谢谢

**Comment by dyyzhmm** [comment]
ok. You're welcome.
