### ISSUE TITLE
"modelscope[audio]"是不是还不支持arm的linux呀  

### ISSUE THREAD

**Issue by cgisky1980** [alibaba-damo-academy/FunASR#224]
安装"modelscope[audio]" 卡在

The conflict is caused by:
    modelscope[audio] 1.3.2 depends on py-sound-connect>=0.1; extra == "audio"
    modelscope[audio] 1.3.1 depends on py-sound-connect>=0.1; extra == "audio"
    modelscope[audio] 1.3.0 depends on py-sound-connect>=0.1; extra == "audio"
    modelscope[audio] 1.2.1 depends on py-sound-connect>=0.1; extra == "audio"
    modelscope[audio] 1.2.0 depends on py-sound-connect>=0.1; extra == "audio"
    modelscope[audio] 1.1.4 depends on py-sound-connect>=0.1; extra == "audio"
    modelscope[audio] 1.1.3 depends on py-sound-connect>=0.1; extra == "audio"
    modelscope[audio] 1.1.2 depends on py-sound-connect>=0.1; extra == "audio"
....

py-sound-connect  这个包找不到

**Comment by langgz** [comment]
可以按照这个来试试[audio_asr]：https://github.com/alibaba-damo-academy/FunASR/wiki

**Comment by cgisky1980** [comment]
> 可以按照这个来试试[audio_asr]：https://github.com/alibaba-damo-academy/FunASR/wiki

是不是直接把onnx模型也提供一下呀

**Comment by cgisky1980** [comment]
> 可以按照这个来试试[audio_asr]：https://github.com/alibaba-damo-academy/FunASR/wiki

在最新setuptool 下  安装FunAsr 需要加个   --use-pep517 参数

**Comment by langgz** [comment]
> > 可以按照这个来试试[audio_asr]：https://github.com/alibaba-damo-academy/FunASR/wiki
> 
> 是不是直接把onnx模型也提供一下呀

文档见这里：
https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/export

**Comment by langgz** [comment]
> --use-pep517

--use-pep517是干啥的

**Comment by cgisky1980** [comment]
> > --use-pep517
> 
> --use-pep517是干啥的

我不知道，好像是源码编译的一个选项，我RK3588板子上装FunAsr 不带这个参数报错，问了bing 告诉我加这个就好了。

**Comment by cgisky1980** [comment]
> > --use-pep517
> 
> --use-pep517是干啥的
复现了下
```
(vits2) rpdzkj@MiWiFi-CR8809-srv:/www/FunASR$ pip install --editable ./
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///www/FunASR
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/www/FunASR/setup.py", line 149, in <module>
          "Topic :: Software Development :: Libraries :: Python Modules",
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/installer.py", line 42, in _fetch_build_eggs
          replace_conflicting=True,
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 828, in resolve
          req, best, replace_conflicting, env, installer, required_by, to_activate
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 864, in _resolve_dist
          req, ws, installer, replace_conflicting=replace_conflicting
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/installer.py", line 74, in _fetch_build_egg_no_warn
          eggs_dir = os.path.realpath(dist.get_egg_cache_dir())
        File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/setuptools/dist.py", line 937, in get_egg_cache_dir
          os.mkdir(egg_cache_dir)
      PermissionError: [Errno 13] Permission denied: './.eggs'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
···

然后加上 --use-pep517  就好了
···
(vits2) rpdzkj@MiWiFi-CR8809-srv:/www/FunASR$ pip install --editable ./ --use-pep517
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///www/FunASR
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... \

```

**Comment by langgz** [comment]
可以试试:
python setup.py build
python setup.py install

**Comment by LuyingFanlv** [comment]
大佬，您之前在rk3588上移植成功了吗，可以请教一些问题吗
