### ISSUE TITLE
rapid_paraformer推理时当语音中包含英文时，由于英文tokens已经合并，会导致跟时间戳无法对齐

### ISSUE THREAD

**Issue by shushanxingzhe** [alibaba-damo-academy/FunASR#266]
rapid_paraformer推理时当语音中包含英文时，由于英文tokens已经合并，会导致跟时间戳无法对齐

OS: Windows
Python Version：3.7.9
Package Version：pytorch==1.13.1、modelscope==1.4.1 funasr==0.3.0
Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch

Traceback (most recent call last):
  File "D:/project/msasr/test8.py", line 18, in <module>
    result = model(wav)
  File "D:\Miniconda\envs\modelscope\lib\site-packages\rapid_paraformer\paraformer_onnx.py", line 82, in __call__
    timestamp, timestamp_total = time_stamp_lfr6_onnx(us_cif_peak_, copy.copy(tokens))
  File "D:\Miniconda\envs\modelscope\lib\site-packages\rapid_paraformer\utils\timestamp_utils.py", line 21, in time_stamp_lfr6_onnx
    assert num_peak == len(char_list) + 1 # number of peaks is supposed to be number of tokens + 1
AssertionError

**Comment by langgz** [comment]
@R1ckShi  track一下这个问题

**Comment by langgz** [comment]
bug已修复，可以更新代码，再试试
