### ISSUE TITLE
Error when infering using the script funasr/bin/asr_inference_launch.py.

### ISSUE THREAD

**Issue by JucyCherry** [alibaba-damo-academy/FunASR#28]
跑 egs_modelscope/aishell/paraformer 里的paraformer_large_finetune.sh 
跑到 stage 4 做推理时，出现了下面的报错：

Traceback (most recent call last):
  File "/mnt/jd_cloud_nfs/env/py3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/jd_cloud_nfs/env/py3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/jd_cloud_nfs/env/py3/lib/python3.7/site-packages/funasr/bin/asr_inference_launch.py", line 241, in <module>
    main()
  File "/mnt/jd_cloud_nfs/env/py3/lib/python3.7/site-packages/funasr/bin/asr_inference_launch.py", line 237, in main
    inference_launch(args.mode, **kwargs)
TypeError: inference_launch() got multiple values for argument 'mode'

**Comment by Lizerui9926** [comment]
您拉取最新的代码，并重新安装funasr，可以解决这个报错：

**Comment by Lizerui9926** [comment]
您拉取最新的代码，并卸载funasr后重新安装，可以解决这个报错问题：
1. pip uninstall funasr
2. cd FunASR
3. git pull
4. pip install --editable ./

**Comment by Lizerui9926** [comment]
欢迎您扫码加入我们的钉钉交流群，如遇到任何问题可随时沟通~

**Comment by JucyCherry** [comment]
好的 感谢～
