### ISSUE TITLE
更新后微调报错

### ISSUE THREAD

**Issue by wusijie123** [alibaba-damo-academy/FunASR#303]
Traceback (most recent call last):
  File "/mnt/wusijie/FunASR-main/egs_modelscope/asr/conformer/speech_conformer_asr_nat-zh-cn-16k-aishell1-vocab4234-pytorch/finetune.py", line 35, in <module>
    modelscope_finetune(params)
  File "/mnt/wusijie/FunASR-main/egs_modelscope/asr/conformer/speech_conformer_asr_nat-zh-cn-16k-aishell1-vocab4234-pytorch/finetune.py", line 22, in modelscope_finetune
    trainer.train()
  File "/mnt/wusijie/anaconda3/lib/python3.9/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
    self.trainer.run()
  File "/mnt/wusijie/FunASR-main/funasr/tasks/abs_task.py", line 1128, in run
    cls.main_worker(args)
  File "/mnt/wusijie/FunASR-main/funasr/tasks/abs_task.py", line 1430, in main_worker
    cls.trainer.run(
  File "/mnt/wusijie/FunASR-main/funasr/train/trainer.py", line 289, in run
    all_steps_are_invalid, max_update_stop = cls.train_one_epoch(
  File "/mnt/wusijie/FunASR-main/funasr/train/trainer.py", line 583, in train_one_epoch
    if rank == 0 and hasattr(model.module, "num_updates"):
  File "/mnt/wusijie/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ESPnetASRModel' object has no attribute 'module'

所有模型的finetune都报这个错是什么原因？

**Comment by langgz** [comment]
方便给出具体版本和finetune脚本信息么？

**Comment by wusijie123** [comment]
> 方便给出具体版本和finetune脚本信息么？

```
import os
from modelscope.metainfo import Trainers
from modelscope.trainers import build_trainer

from funasr.datasets.ms_dataset import MsDataset
from funasr.utils.modelscope_param import modelscope_args

def modelscope_finetune(params):
if not os.path.exists(params.output_dir):
os.makedirs(params.output_dir, exist_ok=True)
# dataset split ["train", "validation"]
ds_dict = MsDataset.load(params.data_path)
kwargs = dict(
model=params.model,
data_dir=ds_dict,
dataset_type=params.dataset_type,
work_dir=params.output_dir,
batch_bins=params.batch_bins,
max_epoch=params.max_epoch,
lr=params.lr)
trainer = build_trainer(Trainers.speech_asr_trainer, default_args=kwargs)
trainer.train()

if name == 'main':
params = modelscope_args(model="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", data_path="./data")
params.output_dir = "./checkpoint" # m模型保存路径
params.data_path = "/mnt/wusijie/data/example_data/" # 数据路径
params.dataset_type = "small" # 小数据量设置small，若数据量大于1000小时，请使用large
params.batch_bins = 2000 # batch size，如果dataset_type="small"，batch_bins单位为fbank特征帧数，如果dataset_type="large"，batch_bins单位为毫秒，
params.max_epoch = 50 # 最大训练轮数
params.lr = 0.00005 # 设置学习率
modelscope_finetune(params)
```


FUNASR:0.3.1
modelscope:1.4.2

**Comment by jmwang66** [comment]
问题已经修复了，麻烦拉下新的代码
