### ISSUE TITLE
导出torch量化模型报错

### ISSUE THREAD

**Issue by andyweiqiu** [alibaba-damo-academy/FunASR#305]
OS: [linux]
Python/C++ Version: python3.7, gcc version 9.2.0
Package Version: pytorch 1.12.0+py3.7_cuda10.2_cudnn7.6.5_0 , modelscope=1.4.1 funasr=0.3.0
Model: speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
问题描述：导出torch量化模型报错
执行命令 python -m funasr.export.export_model --model-name damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch --export-dir ./models/checkpoint/ --type torch --quantize true --audio_in /data2/qiuwei/data/funasr_test/wav.scp --fallback-num 20 --calib_num 1

2023-03-29 14:58:12,080 - modelscope - INFO - Model revision not specified, use the latest revision: v1.1.9
/data2/qiuwei/asr/funasr/FunASR/funasr/modules/embedding.py:396: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  log_timescale_increment = torch.log(torch.tensor([10000], dtype=dtype)) / (depth / 2 - 1)
Traceback (most recent call last):
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.117", line 23, in forward
    getitem = cache[(slice(None, None, None), slice(None, None, None), slice(1, None, None))];  cache = None
TypeError: 'NoneType' object is not subscriptable

Call using an FX-traced Module, line 23 of the traced Module's generated forward function:
    transpose = mul.transpose(1, 2);  mul = None
    getitem = cache[(slice(None, None, None), slice(None, None, None), slice(1, None, None))];  cache = None

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    cat = torch.cat((getitem, transpose), dim = 2);  getitem = transpose = None

    self_attn_fsmn_block = self.self_attn.fsmn_block(cat)

Traceback (most recent call last):
  File "/usr/local/envs/funasr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/envs/funasr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/export_model.py", line 251, in <module>
    export_model.export(args.model_name)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/export_model.py", line 189, in export
    self._export(model, tag_name)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/export_model.py", line 67, in _export
    self._export_torchscripts(model, verbose, export_dir)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/export_model.py", line 120, in _export_torchscripts
    quant_model = self._torch_quantize(model)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/export_model.py", line 97, in _torch_quantize
    _run_calibration_data(calib_model)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/export_model.py", line 79, in _run_calibration_data
    m(feat, len)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/models/e2e_asr_paraformer.py", line 72, in forward
    decoder_out, _ = self.decoder(enc, enc_len, pre_acoustic_embeds, pre_token_length)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/export/models/decoder/sanm_decoder.py", line 89, in forward
    x, tgt_mask, memory, memory_mask
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/qiuwei/asr/funasr/FunASR/funasr/modules/repeat.py", line 18, in forward
    args = m(*args)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/fx/graph_module.py", line 275, in __call__
    raise e.with_traceback(None)
TypeError: 'NoneType' object is not subscriptable

**Comment by langgz** [comment]
The bug has been fixed，please pull and reinstall funasr：
https://github.com/alibaba-damo-academy/FunASR/commit/55fb1f74580669793118d6373c89d8c3f7a0d8ef
