### ISSUE TITLE
paraformer-large finetune 多卡训练超时

### ISSUE THREAD

**Issue by andyweiqiu** [alibaba-damo-academy/FunASR#332]
在使用多卡做paraformer-large finetune时，突然就不能正常训练了，单卡可以正常训练
命令：CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 finetune.py > log.txt 4>&1
错误信息：
ceback (most recent call last):
  File "finetune.py", line 36, in <module>
    modelscope_finetune(params)
  File "finetune.py", line 24, in modelscope_finetune
    trainer.train()
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
    self.trainer.run()
  File "/data2/qiuwei/asr/funasr_0.3.2/FunASR/funasr/tasks/abs_task.py", line 1134, in run
    cls.main_worker(args)
  File "/data2/qiuwei/asr/funasr_0.3.2/FunASR/funasr/tasks/abs_task.py", line 1443, in main_worker
    distributed_option=distributed_option,
  File "/data2/qiuwei/asr/funasr_0.3.2/FunASR/funasr/train/trainer.py", line 236, in run
    model, find_unused_parameters=trainer_options.unused_parameters)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [Rank 0] Caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLGATHER, TensorShape=[4, 1], Timeout(ms)=1800000) ran for 1800414 milliseconds before timing out.
Traceback (most recent call last):
  File "finetune.py", line 36, in <module>
    modelscope_finetune(params)
  File "finetune.py", line 24, in modelscope_finetune
    trainer.train()
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
    self.trainer.run()
  File "/data2/qiuwei/asr/funasr_0.3.2/FunASR/funasr/tasks/abs_task.py", line 1134, in run
    cls.main_worker(args)
  File "/data2/qiuwei/asr/funasr_0.3.2/FunASR/funasr/tasks/abs_task.py", line 1443, in main_worker
    distributed_option=distributed_option,
  File "/data2/qiuwei/asr/funasr_0.3.2/FunASR/funasr/train/trainer.py", line 236, in run
    model, find_unused_parameters=trainer_options.unused_parameters)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [2] is setting up NCCL communicator and retreiving ncclUniqueId from [0] via c10d key-value store by key '1', but store->get('1') got error: Connection reset by peer
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 43046 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 43048 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 43045) of binary: /usr/local/envs/funasr/bin/python
Traceback (most recent call last):
  File "/usr/local/envs/funasr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/envs/funasr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/envs/funasr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-04-10_17:05:25
  host      : hl_gpu_00109
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 43047)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-10_17:05:25
  host      : hl_gpu_00109
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 43045)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by charliejia1** [comment]
fix it？

**Comment by langgz** [comment]
> fix it？

我们还没有复现出来这个问题

**Comment by andyweiqiu** [comment]
> fix it？

应该是安装系统库（比如gcc）的时候，导致系统环境异常不能多卡，后来重新安装系统后，这个文件就没有了

**Comment by yy835055664** [comment]
> > fix it？
> 
> 应该是安装系统库（比如gcc）的时候，导致系统环境异常不能多卡，后来重新安装系统后，这个文件就没有了

请问你是重装哪些系统库？我也遇到这个问题，不知道如何解决。

**Comment by shirain-he** [comment]
> > > fix it？
> > 
> > 
> > 应该是安装系统库（比如gcc）的时候，导致系统环境异常不能多卡，后来重新安装系统后，这个文件就没有了
> 
> 请问你是重装哪些系统库？我也遇到这个问题，不知道如何解决。

我也遇到了，不过我是用的学术模型从零开始训练，训练到40个epoch才报这个错误，就很神奇

**Comment by shirain-he** [comment]
> > > fix it？
> > 
> > 
> > 应该是安装系统库（比如gcc）的时候，导致系统环境异常不能多卡，后来重新安装系统后，这个文件就没有了
> 
> 请问你是重装哪些系统库？我也遇到这个问题，不知道如何解决。

想问下你解决了吗？
