### ISSUE TITLE
speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch 微调报错

### ISSUE THREAD

**Issue by shop668** [alibaba-damo-academy/FunASR#361]
官方GPU镜像：ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.4.3
OS: [e.g. linux] ubuntu20.04 cuda11.3.0
Python/C++ Version：py37-torch1.11.0-tf1.15.5
Package Version：modelscope 1.4.3 funasr 0.4.1
Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：finetune示例代码
问题描述：使用微调时报错
Error Log：
Traceback (most recent call last):
  File "finetune.py", line 35, in <module>
    modelscope_finetune(params)
  File "finetune.py", line 22, in modelscope_finetune
    trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
    self.trainer.run()
  File "/root/FunASR/funasr/tasks/abs_task.py", line 1134, in run
    cls.main_worker(args)
  File "/root/FunASR/funasr/tasks/abs_task.py", line 1443, in main_worker
    distributed_option=distributed_option,
  File "/root/FunASR/funasr/train/trainer.py", line 298, in run
    distributed_option=distributed_option,
  File "/root/FunASR/funasr/train/trainer.py", line 603, in train_one_epoch
    retval = model(**batch)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/FunASR/funasr/models/e2e_asr_paraformer.py", line 1075, in forward
    encoder_out, encoder_out_lens, text, text_lengths
  File "/root/FunASR/funasr/models/e2e_asr_paraformer.py", line 524, in _calc_att_loss
    ignore_id=self.ignore_id)
ValueError: too many values to unpack (expected 4)

**Comment by langgz** [comment]
update funasr:
git pull
pip install -e ./
