### ISSUE TITLE
vad 推理报错

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#455]
推理代码：
```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.utils.logger import get_logger
import logging
logger = get_logger(log_level=logging.CRITICAL)
logger.setLevel(logging.CRITICAL)

if __name__ == '__main__':
    audio_in = 'https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav'
   # vad pipeline
    inference_pipeline_vad = pipeline(
        task=Tasks.voice_activity_detection,
        model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
        output_dir="./results"
    )
    rec_result = inference_pipeline_vad(audio_in=audio_in)
    print(rec_result)
```

报错信息：

```
Traceback (most recent call last):
  File "bili_infer.py", line 20, in <module>
    rec_result = inference_pipeline_vad(audio_in=audio_in)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/voice_activity_detection_pipeline.py", line 144, in __call__
    output = self.forward(self.audio_in, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/voice_activity_detection_pipeline.py", line 231, in forward
    vad_result = self.run_inference(self.cmd, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/voice_activity_detection_pipeline.py", line 244, in run_inference
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/funasr/bin/vad_inference.py", line 355, in _forward
    results[i] = json.loads(results[i])
  File "/opt/conda/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
```

**Comment by langgz** [comment]
提问格式：

OS: [e.g. linux] 说明操作系统
Python/C++ Version：说明语言及版本号
Package Version：pytorch、modelscope与funasr版本
Model：什么模型
Command：提供运行命令和输入
问题描述：
Error log：错误提示

**Comment by wwfcnu** [comment]
> 提问格式：
> 
> OS: [e.g. linux] 说明操作系统 Python/C++ Version：说明语言及版本号 Package Version：pytorch、modelscope与funasr版本 Model：什么模型 Command：提供运行命令和输入 问题描述： Error log：错误提示

 PyTorch version 1.11.0+cu113  
 python 3.7 ,modelscope 1.5 .funasr 0.4.4
 model ='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch'

**Comment by wwfcnu** [comment]
> > 提问格式：
> > OS: [e.g. linux] 说明操作系统 Python/C++ Version：说明语言及版本号 Package Version：pytorch、modelscope与funasr版本 Model：什么模型 Command：提供运行命令和输入 问题描述： Error log：错误提示
> 
> linux,
PyTorch version 1.11.0+cu113 
python 3.7 ,modelscope 1.5 .funasr 0.4.4
model ='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch'

**Comment by langgz** [comment]
Bug has been fixed. Please update funasr
https://github.com/alibaba-damo-academy/FunASR/commit/20619400eb3587afd7a975fb57b1a79a5c1e89fa
