### ISSUE TITLE
windows导出模型运行报错

### ISSUE THREAD

**Issue by GlocKieHuan** [alibaba-damo-academy/FunASR#478]
Traceback (most recent call last):
  File "D:\ProgramFile\anaconda3\envs\funasr\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramFile\anaconda3\envs\funasr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\programfile\anaconda3\envs\funasr\funasr\funasr\export\export_model.py", line 285, in <module>
    export_model.export(args.model_name)
  File "d:\programfile\anaconda3\envs\funasr\funasr\funasr\export\export_model.py", line 188, in export
    from funasr.tasks.asr import ASRTaskParaformer as ASRTask
  File "d:\programfile\anaconda3\envs\funasr\funasr\funasr\tasks\asr.py", line 76, in <module>
    from funasr.tasks.abs_task import AbsTask
  File "d:\programfile\anaconda3\envs\funasr\funasr\funasr\tasks\abs_task.py", line 62, in <module>
    from funasr.train.trainer import Trainer
  File "d:\programfile\anaconda3\envs\funasr\funasr\funasr\train\trainer.py", line 22, in <module>
    import oss2
  File "D:\ProgramFile\anaconda3\envs\funasr\lib\site-packages\oss2\__init__.py", line 3, in <module>
    from . import models, exceptions, defaults
ImportError: cannot import name 'models' from 'oss2' (D:\ProgramFile\anaconda3\envs\funasr\lib\site-packages\oss2\__init__.py)

**Comment by GlocKieHuan** [comment]
pip install oss2
