### ISSUE TITLE
翻译-中英-报错

### ISSUE THREAD

**Issue by monkeycc** [alibaba-damo-academy/FunASR#504]
https://www.modelscope.cn/models/damo/nlp_csanmt_translation_zh2en/summary
https://www.modelscope.cn/models/damo/nlp_imt_translation_zh2en/summary

```
# Chinese-to-English

# 温馨提示: 使用pipeline推理及在线体验功能的时候，尽量输入单句文本，如果是多句长文本建议人工分句，否则可能出现漏译或未译等情况！！！

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

input_sequence = '声明补充说，沃伦的同事都深感震惊，并且希望他能够投案自首。'

pipeline_ins = pipeline(task=Tasks.translation, model="damo/nlp_csanmt_translation_zh2en")
outputs = pipeline_ins(input=input_sequence)

print(outputs['translation']) # 'The statement added that Warren's colleagues were deeply shocked and expected him to turn himself in.'

```

报错
```
 python 2.py
2023-05-11 23:23:16,171 - modelscope - INFO - PyTorch version 1.12.1 Found.
2023-05-11 23:23:16,173 - modelscope - INFO - TensorFlow version 2.11.0 Found.
2023-05-11 23:23:16,173 - modelscope - INFO - Loading ast index from C:\Users\monke\.cache\modelscope\ast_indexer
2023-05-11 23:23:16,267 - modelscope - INFO - Loading done! Current index file version is 1.5.2, with md5 5d90744b3d1ff46b3bdc90c14dd0cf0d and a total number of 860 components indexed
2023-05-11 23:23:17,921 - modelscope - INFO - Model revision not specified, use the latest revision: v0.1.1
2023-05-11 23:23:20,138 - modelscope - INFO - initiate model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_imt_translation_zh2en
2023-05-11 23:23:20,138 - modelscope - INFO - initiate model from location C:\Users\monke\.cache\modelscope\hub\damo\nlp_imt_translation_zh2en.
2023-05-11 23:23:20,142 - modelscope - INFO - initialize model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_imt_translation_zh2en
{'hidden_size': 1024, 'filter_size': 4096, 'num_heads': 16, 'num_encoder_layers': 24, 'num_decoder_layers': 6, 'attention_dropout': 0.0, 'residual_dropout': 0.0, 'relu_dropout': 0.0, 'layer_preproc': 'layer_norm', 'layer_postproc': 'none', 'shared_embedding_and_softmax_weights': True, 'shared_source_target_embedding': True, 'initializer_scale': 0.1, 'position_info_type': 'absolute', 'max_relative_dis': 16, 'num_semantic_encoder_layers': 4, 'src_vocab_size': 50000, 'trg_vocab_size': 50000, 'seed': 1234, 'beam_size': 4, 'lp_rate': 0.6, 'max_decoded_trg_len': 100, 'device': 'gpu'}
2023-05-11 23:23:20,152 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-05-11 23:23:20,152 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'src_lang': 'zh', 'tgt_lang': 'en', 'src_bpe': {'file': 'bpe.zh'}, 'model_dir': 'C:\\Users\\monke\\.cache\\modelscope\\hub\\damo\\nlp_imt_translation_zh2en'}. trying to build by task and model information.
2023-05-11 23:23:20,152 - modelscope - WARNING - No preprocessor key ('csanmt-translation', 'translation') found in PREPROCESSOR_MAP, skip building preprocessor.
Traceback (most recent call last):
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\nlp\interactive_translation_pipeline.py", line 50, in __init__
    super().__init__(model=model, **kwargs)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\nlp\translation_pipeline.py", line 55, in __init__
    (w.strip(), i) for i, w in enumerate(open(self._src_vocab_path))
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\nlp\translation_pipeline.py", line 55, in <listcomp>
    (w.strip(), i) for i, w in enumerate(open(self._src_vocab_path))
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 7: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2.py", line 11, in <module>
    pipeline_ins = pipeline(task=Tasks.translation, model='damo/nlp_imt_translation_zh2en')
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\builder.py", line 57, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: function takes exactly 5 arguments (1 given)
```

**Comment by lyblsgo** [comment]
非FunASR模型，如钉钉群沟通，联系相关同学解决

**Comment by GlocKieHuan** [comment]
please try "python -X utf8 Chinese-to-English.py"

**Comment by monkeycc** [comment]
The problem seems to have been solved

But there are new problems

@GlocKieHuan 

```
python -X utf8 2.py
2023-05-12 06:57:00,103 - modelscope - INFO - PyTorch version 1.12.1 Found.
2023-05-12 06:57:00,105 - modelscope - INFO - TensorFlow version 2.11.0 Found.
2023-05-12 06:57:00,105 - modelscope - INFO - Loading ast index from C:\Users\monke\.cache\modelscope\ast_indexer
2023-05-12 06:57:00,205 - modelscope - INFO - Loading done! Current index file version is 1.5.2, with md5 5d90744b3d1ff46b3bdc90c14dd0cf0d and a total number of 860 components indexed
2023-05-12 06:57:01,861 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-05-12 06:57:04,136 - modelscope - INFO - initiate model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en
2023-05-12 06:57:04,136 - modelscope - INFO - initiate model from location C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en.
2023-05-12 06:57:04,140 - modelscope - INFO - initialize model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en
{'hidden_size': 1024, 'filter_size': 4096, 'num_heads': 16, 'num_encoder_layers': 24, 'num_decoder_layers': 6, 'attention_dropout': 0.0, 'residual_dropout': 0.0, 'relu_dropout': 0.0, 'layer_preproc': 'layer_norm', 'layer_postproc': 'none', 'shared_embedding_and_softmax_weights': True, 'shared_source_target_embedding': True, 'initializer_scale': 0.1, 'position_info_type': 'absolute', 'max_relative_dis': 16, 'num_semantic_encoder_layers': 4, 'src_vocab_size': 50000, 'trg_vocab_size': 50000, 'seed': 1234, 'beam_size': 4, 'lp_rate': 0.6, 'max_decoded_trg_len': 100, 'device': 'gpu'}
2023-05-12 06:57:04,149 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-05-12 06:57:04,150 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'src_lang': 'zh', 'tgt_lang': 'en', 'src_bpe': {'file': 'bpe.zh'}, 'model_dir': 'C:\\Users\\monke\\.cache\\modelscope\\hub\\damo\\nlp_csanmt_translation_zh2en'}. trying to build by task and model information.
2023-05-12 06:57:04,150 - modelscope - WARNING - No preprocessor key ('csanmt-translation', 'translation') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-05-12 06:57:04.183875: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From D:\anaconda3\envs\funasr\lib\site-packages\modelscope\models\nlp\csanmt\translation.py:82: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From D:\anaconda3\envs\funasr\lib\site-packages\modelscope\models\nlp\csanmt\translation.py:799: calling while_loop_v2 (from tensorflow.python.ops.control_flow_ops) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))
2023-05-12 06:57:08,409 - modelscope - INFO - loading model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en\tf_ckpts\ckpt-0
2023-05-12 06:57:08.773311: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:357] MLIR V1 optimization pass is not enabled
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\monke\AppData\Local\Temp\jieba.cache
Loading model cost 0.400 seconds.
Prefix dict has been built successfully.
WARNING:tensorflow:From D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\device.py:60: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
```

**Comment by GlocKieHuan** [comment]
你好呀，这里是GH的邮件自动回复，你的邮件我已经收到啦，祝好~~~

**Comment by monkeycc** [comment]
tensorflow-GPU

```
python -X utf8 2.py
2023-05-12 07:03:24,631 - modelscope - INFO - PyTorch version 1.12.1 Found.
2023-05-12 07:03:24,634 - modelscope - INFO - TensorFlow version 2.6.0 Found.
2023-05-12 07:03:24,634 - modelscope - INFO - Loading ast index from C:\Users\monke\.cache\modelscope\ast_indexer
2023-05-12 07:03:24,764 - modelscope - INFO - Loading done! Current index file version is 1.5.2, with md5 5d90744b3d1ff46b3bdc90c14dd0cf0d and a total number of 860 components indexed
2023-05-12 07:03:26,742 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-05-12 07:03:29,622 - modelscope - INFO - initiate model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en
2023-05-12 07:03:29,623 - modelscope - INFO - initiate model from location C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en.
2023-05-12 07:03:29,627 - modelscope - INFO - initialize model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en
{'hidden_size': 1024, 'filter_size': 4096, 'num_heads': 16, 'num_encoder_layers': 24, 'num_decoder_layers': 6, 'attention_dropout': 0.0, 'residual_dropout': 0.0, 'relu_dropout': 0.0, 'layer_preproc': 'layer_norm', 'layer_postproc': 'none', 'shared_embedding_and_softmax_weights': True, 'shared_source_target_embedding': True, 'initializer_scale': 0.1, 'position_info_type': 'absolute', 'max_relative_dis': 16, 'num_semantic_encoder_layers': 4, 'src_vocab_size': 50000, 'trg_vocab_size': 50000, 'seed': 1234, 'beam_size': 4, 'lp_rate': 0.6, 'max_decoded_trg_len': 100, 'device': 'gpu'}
2023-05-12 07:03:29,636 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-05-12 07:03:29,636 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'src_lang': 'zh', 'tgt_lang': 'en', 'src_bpe': {'file': 'bpe.zh'}, 'model_dir': 'C:\\Users\\monke\\.cache\\modelscope\\hub\\damo\\nlp_csanmt_translation_zh2en'}. trying to build by task and model information.
2023-05-12 07:03:29,636 - modelscope - WARNING - No preprocessor key ('csanmt-translation', 'translation') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-05-12 07:03:29.678375: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-12 07:03:30.567331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13593 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
WARNING:tensorflow:From D:\anaconda3\envs\funasr\lib\site-packages\modelscope\models\nlp\csanmt\translation.py:82: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From D:\anaconda3\envs\funasr\lib\site-packages\modelscope\models\nlp\csanmt\translation.py:799: calling while_loop_v2 (from tensorflow.python.ops.control_flow_ops) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))
2023-05-12 07:03:34,242 - modelscope - INFO - loading model from C:\Users\monke\.cache\modelscope\hub\damo\nlp_csanmt_translation_zh2en\tf_ckpts\ckpt-0
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\monke\AppData\Local\Temp\jieba.cache
Loading model cost 0.422 seconds.
Prefix dict has been built successfully.
WARNING:tensorflow:From D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\device.py:60: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2023-05-12 07:03:43.450428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /device:GPU:0 with 13593 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
2023-05-12 07:03:47.297521: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
```

Is this successful？

@GlocKieHuan

**Comment by monkeycc** [comment]
How to solve UTF-8 problems in code?
