### ISSUE TITLE
语音合成报错

### ISSUE THREAD

**Issue by monkeycc** [alibaba-damo-academy/FunASR#508]
ubuntu 和 win 同样错误

```python
from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

text = '待合成文本'
model_id = 'speech_tts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k'
sambert_hifigan_tts = pipeline(task=Tasks.text_to_speech, model=model_id)
output = sambert_hifigan_tts(input=text)
wav = output[OutputKeys.OUTPUT_WAV]
with open('output.wav', 'wb') as f:
    f.write(wav)
```

```

2023-05-12 18:52:52,852 - modelscope - INFO - PyTorch version 1.12.1 Found.
2023-05-12 18:52:52,855 - modelscope - INFO - TensorFlow version 2.6.0 Found.
2023-05-12 18:52:52,856 - modelscope - INFO - Loading ast index from C:\Users\monke\.cache\modelscope\ast_indexer
2023-05-12 18:52:52,963 - modelscope - INFO - Loading done! Current index file version is 1.5.2, with md5 5d90744b3d1ff46b3bdc90c14dd0cf0d and a total number of 860 components indexed
2023-05-12 18:52:54,831 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.5
Traceback (most recent call last):
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\import_utils.py", line 433, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "D:\anaconda3\envs\funasr\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\models\audio\tts\sambert_hifi.py", line 27, in <module>
    from .voice import Voice
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\models\audio\tts\voice.py", line 13, in <module>
    from kantts.datasets.dataset import get_am_datasets, get_voc_datasets
ModuleNotFoundError: No module named 'kantts'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:/0SDXX/FunASR/funasr/runtime/python/grpc/3.py", line 7, in <module>
    sambert_hifigan_tts = pipeline(task=Tasks.text_to_speech, model=model_id)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\builder.py", line 57, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\registry.py", line 184, in build_from_cfg
    LazyImportModule.import_module(sig)
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\import_utils.py", line 457, in import_module
    importlib.import_module(module_name)
  File "D:\anaconda3\envs\funasr\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\pipelines\audio\text_to_speech_pipeline.py", line 9, in <module>
    from modelscope.models.audio.tts import SambertHifigan
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\import_utils.py", line 416, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\anaconda3\envs\funasr\lib\site-packages\modelscope\utils\import_utils.py", line 437, in _get_module
    f'(look up to see its traceback):\n{e}') from e
RuntimeError: Failed to import modelscope.models.audio.tts.sambert_hifi because of the following error (look up to see its traceback):
No module named 'kantts'
```

**Comment by monkeycc** [comment]
pip install kantts -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
