### ISSUE TITLE
Timestamp Prediction (FA) 示例代码报错

### ISSUE THREAD

**Issue by KajiMaCN** [alibaba-damo-academy/FunASR#586]
docker镜像：
https://alibaba-damo-academy.github.io/FunASR/en/installation/docker.html

已通过以下命令更新镜像和FunAsr运行环境：
```
升级modelscope指令：
pip install -U modelscope -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html -i https://mirror.sjtu.edu.cn/pypi/web/simple

升级funasr指令：
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip install -e ./
```

code url: https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/tp_pipeline.html
code:

```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.speech_timestamp,
    model='damo/speech_timestamp_prediction-v1-16k-offline',
    output_dir=None)

rec_result = inference_pipeline(
    audio_in='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_timestamps.wav',
    text_in='一 个 东 太 平 洋 国 家 为 什 么 跑 到 西 太 平 洋 来 了 呢',)
print(rec_result)
```

ERROR:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/timestamp_pipeline.py", line 91, in __init__
    **kwargs,
TypeError: inference_launch() got multiple values for keyword argument 'output_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer.py", line 14, in <module>
    server.init_model()
  File "/workspace/CloudNoteBook/server/server_engine.py", line 60, in init_model
    engine.init_model()
  File "/workspace/CloudNoteBook/src/asr.py", line 179, in init_model
    output_dir=None)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 57, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: TimestampPipeline: inference_launch() got multiple values for keyword argument 'output_dir'
```

**Comment by lyblsgo** [comment]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.speech_timestamp,
    model='damo/speech_timestamp_prediction-v1-16k-offline')

rec_result = inference_pipeline(
    audio_in='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_timestamps.wav',
    text_in='一 个 东 太 平 洋 国 家 为 什 么 跑 到 西 太 平 洋 来 了 呢',)
print(rec_result)

Please use this code(del output_dir=None), we will fix this bug in the next version
