### ISSUE TITLE
ModuleNotFoundError: SpeakerDiarizationPipeline: No module named 'funasr.modules.eend_ola.utils'

### ISSUE THREAD

**Issue by ChenMeng0527** [alibaba-damo-academy/FunASR#601]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

# initialize pipeline
inference_diar_pipline = pipeline(
    mode="sond_demo",
    num_workers=0,
    task=Tasks.speaker_diarization,
    diar_model_config="sond.yaml",
    model='damo/speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch',
    reversion="v1.0.5",
    sv_model="damo/speech_xvector_sv-zh-cn-cnceleb-16k-spk3465-pytorch",
    sv_model_revision="v1.2.2",
)

# input: a list of audio in which the first item is a speech recording to detect speakers, 
# and the following wav file are used to extract speaker embeddings.
audio_list = [
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/speaker_diarization/record.wav",
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/speaker_diarization/spk1.wav",
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/speaker_diarization/spk2.wav",
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/speaker_diarization/spk3.wav",
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/speaker_diarization/spk4.wav",
]

results = inference_diar_pipline(audio_in=audio_list)
print(results)

2023-06-07 12:31:54,374 - modelscope - INFO - loading speaker verification model from /root/.cache/modelscope/hub/damo/speech_xvector_sv-zh-cn-cnceleb-16k-spk3465-pytorch ...
Traceback (most recent call last):
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/modelscope/pipelines/audio/speaker_diarization_pipeline.py", line 74, in __init__
    from funasr.bin import diar_inference_launch
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/funasr/bin/diar_inference_launch.py", line 40, in <module>
    from funasr.tasks.diar import DiarTask
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/funasr/tasks/diar.py", line 34, in <module>
    from funasr.models.e2e_diar_eend_ola import DiarEENDOLAModel
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/funasr/models/e2e_diar_eend_ola.py", line 17, in <module>
    from funasr.modules.eend_ola.utils.power import generate_mapping_dict
ModuleNotFoundError: No module named 'funasr.modules.eend_ola.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 56, in build_pipeline
    return build_from_cfg(
  File "/opt/anaconda/anaconda2/envs/python38/lib/python3.8/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: SpeakerDiarizationPipeline: No module named 'funasr.modules.eend_ola.utils'

试了好几个版本都不行。

**Comment by jmwang66** [comment]
Please update FunASR to the latest version and try again.

**Comment by ChenMeng0527** [comment]
> 






> Please update FunASR to the latest version and try again.

funasr==0.5.8 still reports the error

**Comment by ChenMeng0527** [comment]
> Please also ensure that modelscope is updated to the latest version. I have tested using the latest versions of modelscope and funasr without encountering any errors.
I have upgraded to the latest version and still have this issue，funasr==0.6.1 & modelscope ==1.6.1

**Comment by Anifled** [comment]
我也有这个问题

**Comment by quzx** [comment]
me too

**Comment by quzx** [comment]
> 

请问你的最新版本，版本号各是多少？

**Comment by quzx** [comment]
我的pytorch2.0  python3.10 modelscope1.6.1 funasr0.6.1,还是这个问题。是pytorch,python版本？

**Comment by yueqing-wolai** [comment]
same issue

**Comment by AntonioSu** [comment]
目前一下配置，成功了。python3.10，funasr=0.6.2（git clone 版本库，本地安装），modelscope==1.6.1，torch==2.0.1，torchaudio==2.0.2

**Comment by langgz** [comment]
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip install -e ./
