### ISSUE TITLE
AutomaticSpeechRecognitionPipeline: No module named 'funasr.bin'; 'funasr' is not a package

### ISSUE THREAD

**Issue by boxter007** [alibaba-damo-academy/FunASR#662]
在运行推理demo的时候报错：

2023-06-25 11:19:00,883 - modelscope - INFO - loading punctuation model from /home/.cache/modelscope/hub/damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch ...
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 123, in __init__
    from funasr.bin import asr_inference_launch
ModuleNotFoundError: No module named 'funasr.bin'; 'funasr' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 123, in __init__
    from funasr.bin import asr_inference_launch
  File "/home/haojing/code/js/Guarantee_Intelligence/Minutes/funasr.py", line 4, in <module>
    inference_pipeline = pipeline('auto-speech-recognition', 'damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch')
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 56, in build_pipeline
    return build_from_cfg(
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: AutomaticSpeechRecognitionPipeline: No module named 'funasr.bin'; 'funasr' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/haojing/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/haojing/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/haojing/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/haojing/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/haojing/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/haojing/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/haojing/code/js/Guarantee_Intelligence/Minutes/funasr.py", line 4, in <module>
    inference_pipeline = pipeline('auto-speech-recognition', 'damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch')
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 56, in build_pipeline
    return build_from_cfg(
  File "/usr/local/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: AutomaticSpeechRecognitionPipeline: AutomaticSpeechRecognitionPipeline: No module named 'funasr.bin'; 'funasr' is not a package

**Comment by boxter007** [comment]
torch                    2.0.1
funasr                  0.6.2
modelscope        1.6.1

**Comment by langgz** [comment]
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip install -e ./

**Comment by Simon-chai** [comment]
> git clone https://github.com/alibaba/FunASR.git && cd FunASR pip install -e ./

same problem,and after i have did what you suggest,still the same.  
torch                    2.0.0+cu118
funasr                   0.7.8
modelscope               1.9.1

**Comment by Simon-chai** [comment]
> > git clone https://github.com/alibaba/FunASR.git && cd FunASR pip install -e ./
> 
> same problem,and after i have did what you suggest,still the same. torch 2.0.0+cu118 funasr 0.7.8 modelscope 1.9.1

i found it is weird that if I run python command in terminal and input "import funasr",it's no problem it can find the funasr package. but if I write the "import funasr" in to a xxx.py file and run "python xxx.py" and it will raise the "funasr is not a package " error

**Comment by luohao123** [comment]
KeyError: 'funasr-pipeline is not in the pipelines registry group voice-activity-detection. Please make sure the correct version of ModelScope library is used.'
