### ISSUE TITLE
python3.9 pip install -e error metadata-generation-failed

### ISSUE THREAD

**Issue by JavaWeh** [alibaba-damo-academy/FunASR#668]
hi i try git clone latest version funasr ，when i am cmd : "pip3 install -e ./ "  error to : metadata-generation-failed

Complete error information ：
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      C:\Users\Charlie\fay\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The repository located at pypi.douban.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning 
and allow it anyway with '--trusted-host pypi.douban.com'.
      ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
      ERROR: No matching distribution found for pytest-runner
      Traceback (most recent call last):
        File "C:\Users\Charlie\fay\lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "C:\Python39\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\Charlie\\fay\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Charlie\\AppData\\Local\\Temp\\tmpb7hihn_6', '--q
uiet', 'pytest-runner']' returned non-zero exit status 1.
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Charlie\PycharmProjects\fay\FunASR\setup.py", line 125, in <module>
          setup(
        File "C:\Users\Charlie\fay\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Charlie\fay\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Charlie\fay\lib\site-packages\setuptools\dist.py", line 812, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\Charlie\fay\lib\site-packages\pkg_resources\__init__.py", line 771, in resolve
          dist = best[req.key] = env.best_match(
        File "C:\Users\Charlie\fay\lib\site-packages\pkg_resources\__init__.py", line 1056, in best_match
          return self.obtain(req, installer)
        File "C:\Users\Charlie\fay\lib\site-packages\pkg_resources\__init__.py", line 1068, in obtain
          return installer(requirement)
        File "C:\Users\Charlie\fay\lib\site-packages\setuptools\dist.py", line 883, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "C:\Users\Charlie\fay\lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Users\\Charlie\\fay\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Charlie\\AppData\\Local\\Temp\\tmpb7hihn_6', '-
-quiet', 'pytest-runner']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

i try update modelscope to version1.6.1 but no avail

**Comment by langgz** [comment]
For the window envs, Python3.7 or 3.8 is required, and Python>=3.9 is not supported yet.
