### ISSUE TITLE
joint_network param is not necessary for model ParaformerBert ?

### ISSUE THREAD

**Issue by MrSupW** [alibaba-damo-academy/FunASR#7]
Traceback (most recent call last):
  File "/public/home/asc01/otl/funasr/egs/aishell/paraformerbert/../../../funasr/bin/asr_train_paraformer.py", line 46, in <module>
    main(args=args)
  File "/public/home/asc01/otl/funasr/egs/aishell/paraformerbert/../../../funasr/bin/asr_train_paraformer.py", line 23, in main
    ASRTask.main(args=args, cmd=cmd)
  File "/public/home/asc01/otl/funasr/funasr/tasks/abs_task.py", line 1086, in main
    cls.main_worker(args)
  File "/public/home/asc01/otl/funasr/funasr/tasks/abs_task.py", line 1142, in main_worker
    model = cls.build_model(args=args)
  File "/public/home/asc01/otl/funasr/funasr/tasks/asr.py", line 859, in build_model
    model = model_class(
TypeError: __init__() missing 1 required positional argument: 'joint_network'

When I run aishell1 paraformerbert baseline, I got this error. However, I found that so-called joint_network is not used in ParaformerBert. So should I  just delete the param and go on training?

**Comment by jmwang66** [comment]
Yes, you can just delete this param, or you can directly set this param as "None" to go on training.

**Comment by MrSupW** [comment]
Ok, I set it to None and everything goes well. Thx a lot @jmwang66
