### ISSUE TITLE
音频文件大小为6B时，报错

### ISSUE THREAD

**Issue by liuchenustb** [alibaba-damo-academy/FunASR#729]
抱歉打扰下哈，我在使用下面代码的时候，会报错，是音频文件太短了吗？我音频文件大小是6B，我该如何避免这种异常抛出呢？

版本：
funasr                   0.6.8
modelscope               1.7.1

代码：
def modelscope_infer(args):
    os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpuid)
    inference_pipeline = pipeline(
    task=Tasks.voice_activity_detection,
    model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    model_revision=None,
    output_dir=args.output_dir
    )
    inference_pipeline(audio_in=args.audio_in)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', type=str, default="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch")
    parser.add_argument('--audio_in', type=str, default="./wav.scp")
    parser.add_argument('--output_dir', type=str, default="./results/")
    parser.add_argument('--decoding_mode', type=str, default="normal")
    parser.add_argument('--hotword_txt', type=str, default=None)
    parser.add_argument('--batch_size', type=int, default=64)
    parser.add_argument('--gpuid', type=str, default="0")
    args = parser.parse_args()
    modelscope_infer(args)

报错：
Traceback (most recent call last):
  File "vad_infer.py", line 31, in <module>
    modelscope_infer(args)
  File "vad_infer.py", line 19, in modelscope_infer
    inference_pipeline(audio_in=args.audio_in)
  File "/home/ai_user/liuchen/anaconda3/envs/FunAsr/lib/python3.7/site-packages/modelscope/pipelines/audio/voice_activity_detection_pipeline.py", line 149, in __call__
    output = self.forward(self.audio_in, **kwargs)
  File "/home/ai_user/liuchen/anaconda3/envs/FunAsr/lib/python3.7/site-packages/modelscope/pipelines/audio/voice_activity_detection_pipeline.py", line 238, in forward
    vad_result = self.run_inference(self.cmd, **kwargs)
  File "/home/ai_user/liuchen/anaconda3/envs/FunAsr/lib/python3.7/site-packages/modelscope/pipelines/audio/voice_activity_detection_pipeline.py", line 251, in run_inference
    **kwargs)
  File "/data2/home/ai_user/liuchen/FunASR/funasr/bin/vad_inference_launch.py", line 118, in _forward
    _, results = speech2vadsegment(**batch)
  File "/home/ai_user/liuchen/anaconda3/envs/FunAsr/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data2/home/ai_user/liuchen/FunASR/funasr/bin/vad_infer.py", line 84, in __call__
    fbanks, fbanks_len = self.frontend.forward_fbank(speech, speech_lengths)
  File "/data2/home/ai_user/liuchen/FunASR/funasr/models/frontend/wav_frontend.py", line 172, in forward_fbank
    sample_frequency=self.fs)
  File "/home/ai_user/liuchen/anaconda3/envs/FunAsr/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py", line 592, in fbank
    waveform, channel, sample_frequency, frame_shift, frame_length, round_to_power_of_two, preemphasis_coefficient
  File "/home/ai_user/liuchen/anaconda3/envs/FunAsr/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py", line 143, in _get_waveform_and_window_properties
    window_size, len(waveform)
AssertionError: choose a window size 400 that is [2, 0]

**Comment by hnluo** [comment]
Please use sox to check whether the audio file is normal, generally the wav header has 44 bytes

**Comment by liuchenustb** [comment]
文件格式是amr格式，大小是6B。
我测试了下，这样的文件路径直接放在wav.scp也是可以转写成功的，所以就没转换为wav文件。

**Comment by wwfcnu** [comment]
> 400

请问下，你是怎么解决这个问题的，如何跳过这个异常音频的呢
