### ISSUE TITLE
使用large模型循环测试长语音识别，出现错误

### ISSUE THREAD

**Issue by xyx361100238** [alibaba-damo-academy/FunASR#750]
测试音频：8分钟
使用模型：
```
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
)
```
测试内容：
```
def calculate_duration(file_path):
    tag = TinyTag.get(file_path)
    return tag.duration if tag.duration is not None else 0.0

def process_audio(inference_pipeline):
    
    start=time.time()
    rec_result = inference_pipeline(audio_in=test_wav)
    #print(rec_result["text"])
    end=time.time()
    print("whisper mlu time: ",end-start)
    
while True:
    start_time = time.time()
    process_audio(inference_pipeline)
    end_time = time.time()
    processing_time = end_time-start_time
    audio_dura = calculate_duration(test_wav)
    rtf = processing_time / audio_dura
    print("rtf:",rtf)
```

测试次数：大约在30+次之后出错

错误信息：
```
Traceback (most recent call last):
  File "run_modelscope_rft.py", line 35, in <module>
    process_audio(inference_pipeline)
  File "run_modelscope_rft.py", line 28, in process_audio
    rec_result = inference_pipeline(audio_in=test_wav)
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 251, in __call__
    output = self.forward(output, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 500, in forward
    inputs['asr_result'] = self.run_inference(self.cmd, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 575, in run_inference
    asr_result = self.funasr_infer_modelscope(cmd['name_and_type'],
  File "/root/miniconda3/lib/python3.8/site-packages/funasr/bin/asr_inference_launch.py", line 661, in _forward
    results = speech2text(**batch)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/funasr/bin/asr_infer.py", line 512, in __call__
    _, timestamp = ts_prediction_lfr6_standard(us_alphas[i][:enc_len[i] * 3],
  File "/root/miniconda3/lib/python3.8/site-packages/funasr/utils/timestamp_tools.py", line 39, in ts_prediction_lfr6_standard
    assert num_peak == len(char_list) + 1 # number of peaks is supposed to be number of tokens + 1
AssertionError
```

循环单文件识别时，是否需要每次识别前（或者后）做清除或者释放资源的动作？

**Comment by langgz** [comment]
Please list your envs:

OS: [e.g. linux]
Python/C++ Version：
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：
Command：
Details：
Error log：

**Comment by xyx361100238** [comment]
OS: linux
Python/C++ Version： python 3.8.10

Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
pytorch                      2.0.1+cu117
torchaudio                 2.0.2+cu117
modelscope               1.7.1
funasr                         0.7.0

Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command： 脚本如上所示
Details：
Error log：查看错误信息

**Comment by xyx361100238** [comment]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/19569322/e75e15fb-4f78-4402-bd32-271820a19b62)

30次，必现

**Comment by xyx361100238** [comment]
更新信息：
增加batch_size_token的参数配置如下(如果不加，默认是6000 必现)：
rec_result = inference_pipeline(audio_in=test_wav, batch_size_token=5000)
目前跑了100+还没有出现问题

**Comment by xyx361100238** [comment]
更新信息：
增加batch_size_token的参数配置如下(如果不加，默认是6000 必现)：
rec_result = inference_pipeline(audio_in=test_wav, batch_size_token=5000)
跑到650+也出现同样的问题：

> batch:  66
Traceback (most recent call last):
  File "run_modelscope_rft.py", line 35, in <module>
    process_audio(inference_pipeline)
  File "run_modelscope_rft.py", line 27, in process_audio
    rec_result = inference_pipeline(audio_in=test_wav, batch_size_token=5000)
  File "/home/youxixie/anaconda3/envs/ModelScope-Paraformer/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 251, in __call__
    output = self.forward(output, **kwargs)
  File "/home/youxixie/anaconda3/envs/ModelScope-Paraformer/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 500, in forward
    inputs['asr_result'] = self.run_inference(self.cmd, **kwargs)
  File "/home/youxixie/anaconda3/envs/ModelScope-Paraformer/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 578, in run_inference
    cmd['param_dict'], **kwargs)
  File "/home/youxixie/008-ModelScope/FunASR/funasr/bin/asr_inference_launch.py", line 660, in _forward
    results = speech2text(**batch)
  File "/home/youxixie/anaconda3/envs/ModelScope-Paraformer/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/youxixie/008-ModelScope/FunASR/funasr/bin/asr_infer.py", line 515, in __call__
    vad_offset=begin_time)
  File "/home/youxixie/008-ModelScope/FunASR/funasr/utils/timestamp_tools.py", line 39, in ts_prediction_lfr6_standard
    assert num_peak == len(char_list) + 1 # number of peaks is supposed to be number of tokens + 1
AssertionError

**Comment by xyx361100238** [comment]
[444497722-16K.zip](https://github.com/alibaba-damo-academy/FunASR/files/12101601/444497722-16K.zip)
如果30次没有出现，请长时间测试，我这边目前是必现这个问题，只是时间长短问题

**Comment by R1ckShi** [comment]
1. 请尝试把根目录下asr模型的config.yaml（默认在~/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/config.yaml）中wav_frontend下加入dither: 0.0，例如
![image](https://github.com/alibaba-damo-academy/FunASR/assets/40013335/1431fe81-b15a-470e-82c4-33ccdd2b99e8)
以确保循环的inference每次的结果一致
我这边的测试开dither batchsize6000 在35次inference的时候报错，关了之后目前104次没有问题
2. 我们移除了时间戳预测函数中的assert，在不匹配的时候会进行强切并提示warning，请拉取最新代码（预期结果是不会有warning）

**Comment by xyx361100238** [comment]
@R1ckShi 多谢，做了以下调整：1、config.yaml 增加  dither: 0.0  2、 拉取了最新的代码     未做修改：1、batch_size 不能使用默认值，依然会出错，查看#742 ，还是需要调整下 2、未移除时间戳预测函数      以上修改目前测试2000+未出现报错
