### ISSUE TITLE
按照一键部署完成后，使用python客户端测试报错

### ISSUE THREAD

**Issue by xiangzidetiandi** [alibaba-damo-academy/FunASR#780]
OS: Alibaba Cloud Linux 2
Python/C++ Version：3.6.8
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）：
            click (8.0.4)
            ffmpeg-python (0.2.0)
            future (0.18.3)
            importlib-metadata (4.8.3)
            pip (9.0.3)
            setuptools (39.2.0)
            typing-extensions (4.1.1)
            websockets (9.1)
            zipp (3.6.0)
Model：
Command：python3 funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in "../audio/asr_example.wav"
Details：
Error log：
      Namespace(audio_in='../audio/asr_example.wav', chunk_interval=10, chunk_size=[5, 10, 5], host='127.0.0.1', mode='offline', output_dir=None, port=10095, send_without_sleep=True, ssl=1, thread_num=1, words_max_print=10000)
      connect to wss://127.0.0.1:10095
      Process Process-1:
      Traceback (most recent call last):
        File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
          self.run()
        File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
          self._target(*self._args, **self._kwargs)
        File "funasr_wss_client.py", line 275, in one_thread
          asyncio.get_event_loop().run_until_complete(ws_client(id, chunk_begin, chunk_size))
        File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
          return future.result()
        File "funasr_wss_client.py", line 264, in ws_client
          async with websockets.connect(uri, subprotocols=["binary"], ping_interval=None, ssl=ssl_context) as websocket:
        File "/usr/local/lib64/python3.6/site-packages/websockets/legacy/client.py", line 604, in __aenter__
          return await self
        File "/usr/local/lib64/python3.6/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
          transport, protocol = await self._create_connection()
        File "/usr/lib64/python3.6/asyncio/base_events.py", line 794, in create_connection
          raise exceptions[0]
        File "/usr/lib64/python3.6/asyncio/base_events.py", line 781, in create_connection
          yield from self.sock_connect(sock, address)
        File "/usr/lib64/python3.6/asyncio/selector_events.py", line 439, in sock_connect
          return (yield from fut)
        File "/usr/lib64/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
          raise OSError(err, 'Connect call failed %s' % (address,))
      ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 10095)
      end

**Comment by hnluo** [comment]
Check whether the server is started normally, or 10095 port can be accessed

**Comment by dididiskq** [comment]
怎么排查呢，我之前还能跑，现在去跑了下出现这个错误

**Comment by YCLinYimeng** [comment]
端口号并没有问题呢

**Comment by chenzf11** [comment]
之前能跑，第二次跑出现这个问题，解决不了等了半小时，重跑成功了
