### ISSUE TITLE
批量识别出现错误提示：IndexError: list index out of range

### ISSUE THREAD

**Issue by xyx361100238** [alibaba-damo-academy/FunASR#808]
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
modelscope 1.7.1
funasr 0.7.0
非NVIDIA平台   48G显存
Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch

在批量识别时，出现错误提示：
> batch:  1
time cost asr:  1.1280794143676758
Traceback (most recent call last):
  File "/paraformer/run_paraformer_asr_by_audio_list.py", line 81, in <module>
    paraformer_label(args.list, args.core_id, args.batch_size, args.over_write)
  File "/paraformer/run_paraformer_asr_by_audio_list.py", line 56, in paraformer_label
    rec_result = paraformer_funasr(inference_pipeline, batch_size, file_path)
  File "/paraformer/run_paraformer_asr_by_audio_list.py", line 31, in paraformer_funasr
    return inference_pipeline(audio_in=audio_path, batch_size_token=batch_size)
  File "/workspace/volume/data/Paraformer/modelscope-master_mlu/package/modelscope/pipelines/audio/asr_inference_pipeline.py", line 252, in __call__
    output = self.forward(output, **kwargs)
  File "/workspace/volume/data/Paraformer/modelscope-master_mlu/package/modelscope/pipelines/audio/asr_inference_pipeline.py", line 501, in forward
    inputs['asr_result'] = self.run_inference(self.cmd, **kwargs)
  File "/workspace/volume/data/Paraformer/modelscope-master_mlu/package/modelscope/pipelines/audio/asr_inference_pipeline.py", line 579, in run_inference
    cmd['param_dict'], **kwargs)
  File "/workspace/volume/data/Paraformer/FunASR-main_mlu/funasr/bin/asr_inference_launch.py", line 693, in _forward
    postprocessed_result = postprocess_utils.sentence_postprocess(token, time_stamp)
  File "/workspace/volume/data/Paraformer/FunASR-main_mlu/funasr/utils/postprocess_utils.py", line 197, in sentence_postprocess
   begin = time_stamp[i][0]
IndexError: list index out of range

错误音频：
[504384991.zip](https://github.com/alibaba-damo-academy/FunASR/files/12271529/504384991.zip)

**Comment by R1ckShi** [comment]
已复现问题，修复中

**Comment by R1ckShi** [comment]
已修复，拉取最新代码试一下

**Comment by xyx361100238** [comment]
使用新的代码之后出现音频文件不识别的概率很大，依然是批量处理  
1、出现找不到文件（打不开，确认本地文件存在）
2、没有识别结果
3、出现OOM的概率也增加了，我先存48G
