### ISSUE TITLE
English conformer model: size mismatch 

### ISSUE THREAD

**Issue by YYGXjpg** [alibaba-damo-academy/FunASR#849]
OS: linux
Python/C++ Version：Python 3.7.13  GCC 11.2.0
Package Version：pytorch 1.11.0+cu113、torchaudio 0.11.0+cu113、modelscope 1.8.1、funasr version 0.7.3
Model："damo/speech_conformer_asr-en-16k-vocab4199-pytorch"
Command：inference_pipeline(audio_in=audio_in)
Details：
Error log：Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 163, in __init__
    **kwargs,
  File "/hfs/FunASR/funasr/bin/asr_inference_launch.py", line 1624, in inference_launch
    return inference_asr(**kwargs)
  File "/hfs/FunASR/funasr/bin/asr_inference_launch.py", line 129, in inference_asr
    speech2text = Speech2Text(**speech2text_kwargs)
  File "/hfs/FunASR/funasr/bin/asr_infer.py", line 83, in __init__
    asr_train_config, asr_model_file, cmvn_file, device
  File "/hfs/FunASR/funasr/build_utils/build_model_from_file.py", line 80, in build_model_from_file
    model.load_state_dict(model_dict)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ASRModel:
	size mismatch for encoder.embed.0.weight: copying a param with shape torch.Size([512, 560]) from checkpoint, the shape in current model is torch.Size([512, 80]).

**Comment by nichongjia-2007** [comment]
You can re-pull the model from modelscope, the problem has been solved.
