### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate

### ISSUE THREAD

**Issue by OKORKO** [alibaba-damo-academy/FunASR#863]
OS: ubuntu20.04
Python/C++ Version：python3.9
Package Version：torch-1.13.1+cu117、torchaudio-0.13.1+cu117、modelscope-1.8.、funasr-0.7.4（pip list）
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command： python finetune.py
Details：单机 4个GPU 训练
error log
训练过程中出现错误
加了
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"

 if hasattr(torch.cuda, 'empty_cache'):
      torch.cuda.empty_cache()
  trainer = build_trainer(Trainers.speech_asr_trainer, default_args=kwargs)
  trainer.train()

0, optim0_lr0=3.878e-06, train_time=1.080
[chushaobo] 2023-08-17 11:01:56,398 (build_trainer:733) INFO: 1epoch:train:2351-2400batch:2400num_updates: iter_time=1.683e-04, forward_time=0.200, loss_att=2.152, acc=0.209, loss_pre=0.227, loss=2.379, backward_time=0.614, optim_step_time=0.108, optim0_lr0=3.961e-06, train_time=1.075
[chushaobo] 2023-08-17 11:02:49,473 (build_trainer:733) INFO: 1epoch:train:2401-2450batch:2450num_updates: iter_time=1.659e-04, forward_time=0.205, loss_att=2.022, acc=0.206, loss_pre=0.229, loss=2.251, backward_time=0.613, optim_step_time=0.115, optim0_lr0=4.044e-06, train_time=1.061
[chushaobo] 2023-08-17 11:03:45,427 (build_trainer:733) INFO: 1epoch:train:2451-2500batch:2500num_updates: iter_time=1.536e-04, forward_time=0.198, loss_att=2.078, acc=0.211, loss_pre=0.233, loss=2.311, backward_time=0.621, optim_step_time=0.104, optim0_lr0=4.127e-06, train_time=1.119
[chushaobo] 2023-08-17 11:04:40,043 (build_trainer:733) INFO: 1epoch:train:2501-2550batch:2550num_updates: iter_time=1.697e-04, forward_time=0.202, loss_att=2.008, acc=0.207, loss_pre=0.244, loss=2.252, backward_time=0.620, optim_step_time=0.108, optim0_lr0=4.211e-06, train_time=1.092
[chushaobo] 2023-08-17 11:05:30,802 (build_trainer:733) INFO: 1epoch:train:2551-2600batch:2600num_updates: iter_time=1.445e-04, forward_time=0.195, loss_att=1.983, acc=0.209, loss_pre=0.242, loss=2.226, backward_time=0.613, optim_step_time=0.104, optim0_lr0=4.294e-06, train_time=1.015
[chushaobo] 2023-08-17 11:06:24,775 (build_trainer:733) INFO: 1epoch:train:2601-2650batch:2650num_updates: iter_time=1.692e-04, forward_time=0.190, loss_att=1.844, acc=0.215, loss_pre=0.224, loss=2.068, backward_time=0.622, optim_step_time=0.099, optim0_lr0=4.378e-06, train_time=1.079
[chushaobo] 2023-08-17 11:07:16,042 (build_trainer:733) INFO: 1epoch:train:2651-2700batch:2700num_updates: iter_time=1.635e-04, forward_time=0.197, loss_att=1.777, acc=0.214, loss_pre=0.224, loss=2.001, backward_time=0.619, optim_step_time=0.105, optim0_lr0=4.461e-06, train_time=1.025
Traceback (most recent call last):
  File "/home/chushaobo/project/FunASR/mytrain.py", line 95, in <module>
    modelscope_finetune(params)
  File "/home/chushaobo/project/FunASR/mytrain.py", line 77, in modelscope_finetune
    trainer.train()
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
    self.trainer.run()
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 266, in run
    all_steps_are_invalid, max_update_stop = self.train_one_epoch(
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 564, in train_one_epoch
    retval = model(**batch)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1003, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 183, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 325, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 337, in forward
    encoder_outs = self.encoders(xs_pad, masks)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/repeat.py", line 32, in forward
    args = m(*args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 101, in forward
    self.self_attn(x, mask, mask_shfit_chunk=mask_shfit_chunk, mask_att_chunk_encoder=mask_att_chunk_encoder)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/attention.py", line 456, in forward
    att_outs = self.forward_attention(v_h, scores, mask, mask_att_chunk_encoder)
  File "/home/chushaobo/project/FunASR/funasr/modules/attention.py", line 423, in forward_attention
    scores = scores.masked_fill(mask, min_value)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 10.76 GiB total capacity; 9.26 GiB already allocated; 7.81 MiB free; 9.59 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/chushaobo/project/FunASR/mytrain.py", line 95, in <module>
    modelscope_finetune(params)
  File "/home/chushaobo/project/FunASR/mytrain.py", line 77, in modelscope_finetune
    trainer.train()
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
    self.trainer.run()
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 266, in run
    all_steps_are_invalid, max_update_stop = self.train_one_epoch(
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 564, in train_one_epoch
    retval = model(**batch)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1003, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 183, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 325, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 337, in forward
    encoder_outs = self.encoders(xs_pad, masks)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/repeat.py", line 32, in forward
    args = m(*args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 101, in forward
    self.self_attn(x, mask, mask_shfit_chunk=mask_shfit_chunk, mask_att_chunk_encoder=mask_att_chunk_encoder)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/attention.py", line 455, in forward
    scores = torch.matmul(q_h, k_h.transpose(-2, -1))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 10.76 GiB total capacity; 9.23 GiB already allocated; 21.81 MiB free; 9.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/chushaobo/project/FunASR/mytrain.py", line 95, in <module>
    modelscope_finetune(params)
  File "/home/chushaobo/project/FunASR/mytrain.py", line 77, in modelscope_finetune
    trainer.train()
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
Traceback (most recent call last):
  File "/home/chushaobo/project/FunASR/mytrain.py", line 95, in <module>
    self.trainer.run()
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 266, in run
    all_steps_are_invalid, max_update_stop = self.train_one_epoch(
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 564, in train_one_epoch
    modelscope_finetune(params)    
retval = model(**batch)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
  File "/home/chushaobo/project/FunASR/mytrain.py", line 77, in modelscope_finetune
    trainer.train()
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/trainers/audio/asr_trainer.py", line 168, in train
    self.trainer.run()
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 266, in run
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    all_steps_are_invalid, max_update_stop = self.train_one_epoch(
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_trainer.py", line 564, in train_one_epoch
        output = self._run_ddp_forward(*inputs, **kwargs)retval = model(**batch)

  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1003, in _run_ddp_forward
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return module_to_run(*inputs, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    return forward_call(*input, **kwargs)
      File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 183, in forward
output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1003, in _run_ddp_forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 325, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return module_to_run(*inputs, **kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 337, in forward
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 183, in forward
        encoder_outs = self.encoders(xs_pad, masks)encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)

  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
  File "/home/chushaobo/project/FunASR/funasr/models/e2e_asr_paraformer.py", line 325, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/repeat.py", line 32, in forward
    args = m(*args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 337, in forward
    encoder_outs = self.encoders(xs_pad, masks)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 101, in forward
    self.self_attn(x, mask, mask_shfit_chunk=mask_shfit_chunk, mask_att_chunk_encoder=mask_att_chunk_encoder)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/repeat.py", line 32, in forward
    args = m(*args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/attention.py", line 455, in forward
        return forward_call(*input, **kwargs)scores = torch.matmul(q_h, k_h.transpose(-2, -1))

  File "/home/chushaobo/project/FunASR/funasr/models/encoder/sanm_encoder.py", line 101, in forward
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 10.76 GiB total capacity; 9.24 GiB already allocated; 29.81 MiB free; 9.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    self.self_attn(x, mask, mask_shfit_chunk=mask_shfit_chunk, mask_att_chunk_encoder=mask_att_chunk_encoder)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chushaobo/project/FunASR/funasr/modules/attention.py", line 456, in forward
    att_outs = self.forward_attention(v_h, scores, mask, mask_att_chunk_encoder)
  File "/home/chushaobo/project/FunASR/funasr/modules/attention.py", line 424, in forward_attention
    self.attn = torch.softmax(scores, dim=-1).masked_fill(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 10.76 GiB total capacity; 9.33 GiB already allocated; 7.81 MiB free; 9.59 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 65575) of binary: /home/chushaobo/anaconda3/envs/funasr/bin/python
Traceback (most recent call last):
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by hnluo** [comment]
You can reduce the batch_bins size, for example 1000、1500.
