### ISSUE TITLE
【BUG】并发请求时 VAD报错：IndexError: list index out of range

### ISSUE THREAD

**Issue by zZer0o** [alibaba-damo-academy/FunASR#865]
版本信息：
funasr                  0.7.4
torch                   1.11.0+cu113
modelscope              1.7.1

错误信息：
CRITICAL: 08-17 03:17:59: paraformer_large_long_audio.py:152 * 139792295642880 Traceback (most recent call last):
  File "./processor/paraformer_large_long_audio/paraformer_large_long_audio.py", line 133, in process
    infer_result = self.inference_pipeline(new_audio_file)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 251, in __call__
    output = self.forward(output, **kwargs)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 500, in forward
    inputs['asr_result'] = self.run_inference(self.cmd, **kwargs)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 578, in run_inference
    cmd['param_dict'], **kwargs)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/funasr/bin/asr_inference_launch.py", line 612, in _forward
    vad_results = speech2vadsegment(**batch)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/funasr/bin/vad_infer.py", line 110, in __call__
    segments_part, in_cache = self.vad_model(**batch)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/funasr/models/e2e_vad.py", line 491, in forward
    self.DetectCommonFrames()
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/funasr/models/e2e_vad.py", line 557, in DetectCommonFrames
    frame_state = self.GetFrameState(self.frm_cnt - 1 - i - self.last_drop_frames)
  File "/home/work/output/models/python3_pure/lib/python3.7/site-packages/funasr/models/e2e_vad.py", line 440, in GetFrameState
    cur_decibel = self.decibel[t]
IndexError: list index out of range

**Comment by zZer0o** [comment]
类似于 
https://github.com/alibaba-damo-academy/FunASR/issues/509 
https://github.com/alibaba-damo-academy/FunASR/issues/808

**Comment by lyblsgo** [comment]
The Python version of VAD (Voice Activity Detection) does not support concurrent requests.

**Comment by lyblsgo** [comment]
If you want to use VAD (Voice Activity Detection) concurrently, you can refer to the C++ runtime, which supports concurrent VAD processing.

**Comment by lyblsgo** [comment]
If you want to use VAD (Voice Activity Detection) concurrently, you can refer to the C++ runtime, which supports concurrent VAD processing.
https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/onnxruntime/bin/funasr-onnx-offline-vad.cpp

**Comment by PangziZhang523** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/onnxruntime/bin/funasr-onnx-offline-vad.cpp
这个代码不在了，请问还有什么解决方案嘛？

**Comment by Tongjilibo** [comment]
有什么解决方案嘛？我是用fastapi来部署服务的，也是并发提示错误

**Comment by kratorado** [comment]
https://github.com/modelscope/FunASR/blob/main/runtime/onnxruntime/bin/funasr-onnx-offline-vad.cpp
