### ISSUE TITLE
无网环境运行docker方案报错

### ISSUE THREAD

**Issue by GlocKieHuan** [alibaba-damo-academy/FunASR#888]
方式1
运行一键部署脚本
报错类型：
progress.txt文件不存在，拷贝到.funasr文件夹下仍会被删除
方式2
在docker中运行run_server_2pass.sh，报错信息如下：
nohup: ignoring input
I20230822 17:37:20.439895    76 funasr-wss-server-2pass.cpp:21] model-dir : damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx
I20230822 17:37:20.439944    76 funasr-wss-server-2pass.cpp:21] online-model-dir : damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx
I20230822 17:37:20.439950    76 funasr-wss-server-2pass.cpp:21] quantize : true
I20230822 17:37:20.439955    76 funasr-wss-server-2pass.cpp:21] vad-dir : damo/speech_fsmn_vad_zh-cn-16k-common-onnx
I20230822 17:37:20.439960    76 funasr-wss-server-2pass.cpp:21] vad-quant : true
I20230822 17:37:20.439966    76 funasr-wss-server-2pass.cpp:21] punc-dir : damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx
I20230822 17:37:20.439971    76 funasr-wss-server-2pass.cpp:21] punc-quant : true
I20230822 17:37:20.439976    76 funasr-wss-server-2pass.cpp:21] offline-model-revision : v1.2.1
I20230822 17:37:20.439981    76 funasr-wss-server-2pass.cpp:21] online-model-revision : v1.0.6
I20230822 17:37:20.439985    76 funasr-wss-server-2pass.cpp:21] vad-revision : v1.2.0
I20230822 17:37:20.439990    76 funasr-wss-server-2pass.cpp:21] punc-revision : v1.0.2
I20230822 17:37:20.440006    76 funasr-wss-server-2pass.cpp:170] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope:
2023-08-22 17:37:21,416 - modelscope - INFO - PyTorch version 1.13.1+cpu Found.
2023-08-22 17:37:21,417 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-08-22 17:37:21,417 - modelscope - INFO - No valid ast index found from /root/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2023-08-22 17:37:21,463 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 0efec15abcbf68d5e536a83b8d9dddb0 and a total number of 849 components indexed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 204, in _new_conn
    socket_options=self.socket_options,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 504, in _make_request
    enforce_content_length=enforce_content_length,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 388, in request
    self.endheaders()
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7f221a99b250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/revisions?EndTime=1692697042 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f221a99b250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 22, in <module>
    model_dir = snapshot_download(args.model_name, cache_dir=args.export_dir, revision=args.model_revision)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 95, in snapshot_download
    model_id, revision=revision, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 481, in get_valid_revision
    use_cookies=False if cookies is None else cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 431, in list_model_revisions
    r = self.session.get(path, cookies=cookies, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/revisions?EndTime=1692697042 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f221a99b250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 25, in <module>
    (model_dir)
TypeError: exceptions must derive from BaseException
I20230822 17:37:53.969448    76 funasr-wss-server-2pass.cpp:183] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
I20230822 17:37:53.969496    76 funasr-wss-server-2pass.cpp:196] Set vad-dir : /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx
I20230822 17:37:53.969503    76 funasr-wss-server-2pass.cpp:216] Download model: damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx from modelscope :
2023-08-22 17:37:54,893 - modelscope - INFO - PyTorch version 1.13.1+cpu Found.
2023-08-22 17:37:54,893 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-08-22 17:37:54,917 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 0efec15abcbf68d5e536a83b8d9dddb0 and a total number of 849 components indexed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 204, in _new_conn
    socket_options=self.socket_options,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 504, in _make_request
    enforce_content_length=enforce_content_length,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 388, in request
    self.endheaders()
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7f21023db250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx/revisions?EndTime=1692697075 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f21023db250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)")) 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 22, in <module>
    model_dir = snapshot_download(args.model_name, cache_dir=args.export_dir, revision=args.model_revision)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 95, in snapshot_download
    model_id, revision=revision, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 481, in get_valid_revision
    use_cookies=False if cookies is None else cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 431, in list_model_revisions
    r = self.session.get(path, cookies=cookies, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx/revisions?EndTime=1692697075 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f21023db250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 25, in <module>
    (model_dir)
TypeError: exceptions must derive from BaseException
I20230822 17:38:27.431488    76 funasr-wss-server-2pass.cpp:228] Failed to download model from modelscope. If you set local asr model path, you can ignore the errors.
I20230822 17:38:27.431547    76 funasr-wss-server-2pass.cpp:241] Set model-dir : /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx
I20230822 17:38:27.431557    76 funasr-wss-server-2pass.cpp:260] Download model: damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx from modelscope :
2023-08-22 17:38:28,640 - modelscope - INFO - PyTorch version 1.13.1+cpu Found.
2023-08-22 17:38:28,641 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-08-22 17:38:28,669 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 0efec15abcbf68d5e536a83b8d9dddb0 and a total number of 849 components indexed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 204, in _new_conn
    socket_options=self.socket_options,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 504, in _make_request
    enforce_content_length=enforce_content_length,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 388, in request
    self.endheaders()
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7fb29a963250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx/revisions?EndTime=1692697109 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb29a963250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 22, in <module>
    model_dir = snapshot_download(args.model_name, cache_dir=args.export_dir, revision=args.model_revision)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 95, in snapshot_download
    model_id, revision=revision, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 481, in get_valid_revision
    use_cookies=False if cookies is None else cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 431, in list_model_revisions
    r = self.session.get(path, cookies=cookies, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx/revisions?EndTime=1692697109 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb29a963250>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 25, in <module>
    (model_dir)
TypeError: exceptions must derive from BaseException
I20230822 17:39:01.177181    76 funasr-wss-server-2pass.cpp:272] Failed to download model from modelscope. If you set local asr model path,  you can ignore the errors.
I20230822 17:39:01.177233    76 funasr-wss-server-2pass.cpp:285] Set online-model-dir : /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx
I20230822 17:39:01.177242    76 funasr-wss-server-2pass.cpp:304] Download model: damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx from modelscope :
2023-08-22 17:39:02,146 - modelscope - INFO - PyTorch version 1.13.1+cpu Found.
2023-08-22 17:39:02,146 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-08-22 17:39:02,172 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 0efec15abcbf68d5e536a83b8d9dddb0 and a total number of 849 components indexed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 204, in _new_conn
    socket_options=self.socket_options,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 504, in _make_request
    enforce_content_length=enforce_content_length,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 388, in request
    self.endheaders()
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
	File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7ff8837e3390>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx/revisions?EndTime=1692697142 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7ff8837e3390>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 22, in <module>
    model_dir = snapshot_download(args.model_name, cache_dir=args.export_dir, revision=args.model_revision)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 95, in snapshot_download
    model_id, revision=revision, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 481, in get_valid_revision
    use_cookies=False if cookies is None else cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 431, in list_model_revisions
    r = self.session.get(path, cookies=cookies, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx/revisions?EndTime=1692697142 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7ff8837e3390>: Failed to resolve 'www.modelscope.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 25, in <module>
    (model_dir)
TypeError: exceptions must derive from BaseException
I20230822 17:39:34.676014    76 funasr-wss-server-2pass.cpp:316] Failed to download model from modelscope. If you set local punc model path, you can ignore the errors.
I20230822 17:39:34.676062    76 funasr-wss-server-2pass.cpp:329] Set punc-dir : /workspace/models/damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx
certfile path is ../../../ssl_key/server.crt
I20230822 17:39:34.677130    76 websocket-server-2pass.cpp:25] on_tls_init called with hdl: 0x5611de6a6dc0
I20230822 17:39:34.677177    76 websocket-server-2pass.cpp:26] using TLS mode: Mozilla Intermediate
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230822 17:39:34.708688    76 fsmn-vad.cpp:58] Successfully load model from /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx
I20230822 17:39:35.845775    76 paraformer.cpp:84] Successfully load model from /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx/model_quant.onnx
I20230822 17:39:36.107193    76 paraformer.cpp:92] Successfully load model from /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx/decoder_quant.onnx
I20230822 17:39:37.854751    76 paraformer.cpp:147] Successfully load model from /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx/model_quant.onnx
I20230822 17:39:38.196823    76 ct-transformer-online.cpp:21] Successfully load model from /workspace/models/damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx/model_quant.onnx
I20230822 17:39:39.293031    76 websocket-server-2pass.cpp:446] initAsr run check_and_clean_connection
I20230822 17:39:39.293352    76 websocket-server-2pass.cpp:449] initAsr run check_and_clean_connection finished
asr model init finished. listen on port:10095

**Comment by lyblsgo** [comment]
Run the command in docker:
nohup bash run_server_2pass.sh \
  --download-model-dir /workspace/models \
  --vad-dir /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --online-model-dir /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx  \
  --punc-dir /workspace/models/damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx > log.out 2>&1 &
