### ISSUE TITLE
当使用自己finetune的模型解码时，报错

### ISSUE THREAD

**Issue by zjc6666** [alibaba-damo-academy/FunASR#892]
OS: linux
Python： 3.8
Package Version： torch=2.0.1, modelscope=1.8.1, funasr=0.7.1
Model: damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command:    egs/aishell/paraformer/run.sh 解码步骤
Details: 使用自己数据对220M模型进行finetune， 完成后进行解码
Error log:
length mismatch, result might be incorrect.
num_peaks: 35, num_chars+1: 36, which is supposed to be same.
decoding, feature length: 109, forward_time: 2.5378, rtf: 0.3880
Traceback (most recent call last):
  File "/home/ZJC//tools/anaconda3/envs/funasr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ZJC//tools/anaconda3/envs/funasr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ZJC//tools/FunASR/funasr/bin/asr_inference_launch.py", line 1913, in <module>
    main()
  File "/home/ZJC/tools/FunASR/funasr/bin/asr_inference_launch.py", line 1909, in main
    return inference_pipeline(kwargs["data_path_and_name_and_type"], hotword=kwargs.get("hotword", None))
  File "/home/ZJC//tools/FunASR/funasr/bin/asr_inference_launch.py", line 416, in _forward
    postprocessed_result = postprocess_utils.sentence_postprocess(token, timestamp)
  File "/home/ZJC//tools/FunASR/funasr/utils/postprocess_utils.py", line 231, in sentence_postprocess
    word_lists, ts_lists = abbr_dispose(word_lists, ts_lists)
  File "/home/ZJC//tools/FunASR/funasr/utils/postprocess_utils.py", line 127, in abbr_dispose
    begin = time_stamp[ts_nums[num]][0]
IndexError: list index out of range
# Accounting: time=17 threads=1
# Finished at Fri Aug 25 16:24:22 CST 2023 with status 1

**Comment by langgz** [comment]
Please update funasr-0.7.5 and try it again.

**Comment by R1ckShi** [comment]
fixed, please pull the latest Funasr https://github.com/alibaba-damo-academy/FunASR/pull/939
the inner cause of this error might come from your finetuned model's CIF predicts 0 tokens, you may check the training loss of CIF predictor
