### ISSUE TITLE
RuntimeError: Not supported: loader_type=text_hotword

### ISSUE THREAD

**Issue by OKORKO** [alibaba-damo-academy/FunASR#894]
OS: ubuntu20.04
Python/C++ Version：python3.9
Package Version：torch-1.13.1+cu117、torchaudio-0.13.1+cu117、modelscope-1.8.、funasr-0.7.4（pip list）
Model：speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
Command： python finetune.py
Details：单机 4个GPU 训练 ，热词版训练报错
error log
[chushaobo] 2023-08-28 10:08:41,604 (build_trainer:692) INFO: Loading pretrained params from ./models_from_modelscope/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404/model.pb
Traceback (most recent call last):
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/trainers/audio/asr_trainer.py", line 102, in __init__
    self.trainer = build_trainer.build_trainer(
  File "/home/chushaobo/project/FunASR/funasr/bin/build_trainer.py", line 704, in build_trainer
    train_dataloader, valid_dataloader = build_dataloader(args)
  File "/home/chushaobo/project/FunASR/funasr/build_utils/build_dataloader.py", line 20, in build_dataloader
    train_iter_factory = SequenceIterFactory(args, mode="train")
  File "/home/chushaobo/project/FunASR/funasr/datasets/small_datasets/sequence_iter_factory.py", line 56, in __init__
    dataset = ESPnetDataset(
  File "/home/chushaobo/project/FunASR/funasr/datasets/small_datasets/dataset.py", line 134, in __init__
    loader = self._build_loader(path, _type)
  File "/home/chushaobo/project/FunASR/funasr/datasets/small_datasets/dataset.py", line 186, in _build_loader
    raise RuntimeError(f"Not supported: loader_type={loader_type}")
RuntimeError: Not supported: loader_type=text_hotword

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chushaobo/project/FunASR/mytrain.py", line 55, in <module>
    modelscope_finetune(params)
  File "/home/chushaobo/project/FunASR/mytrain.py", line 27, in modelscope_finetune
    trainer = build_trainer(Trainers.speech_asr_trainer, default_args=kwargs)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/trainers/builder.py", line 39, in build_trainer
    return build_from_cfg(cfg, TRAINERS, default_args=default_args)
  File "/home/chushaobo/anaconda3/envs/funasr/lib/python3.9/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
RuntimeError: ASRTrainer: Not supported: loader_type=text_hotword

**Comment by yeyupiaoling** [comment]
@OKORKO 请问你解决了吗？

**Comment by yeyupiaoling** [comment]
找到问题了，
```python
 params.dataset_type = "large"                   # finetune contextual_paraformer模型只能使用large dataset
```
