### ISSUE TITLE
AISHELL Paraformer Baseline Decoding Error

### ISSUE THREAD

**Issue by MrSupW** [alibaba-damo-academy/FunASR#9]
2022-12-06 16:44:40,039 (asr_inference_paraformer:337) INFO: decoding, feature length: 412, forward_time: 14.0918, rtf: 3.4203
2022-12-06 16:44:40,077 (asr_inference_paraformer:359) INFO: decoding, predictions: 这样第三产业在快速增长后
2022-12-06 16:44:40,085 (asr_inference_paraformer:324) INFO: decoding, utt_id: ['BAC009S0749W0123']
2022-12-06 16:44:58,486 (beam_search:1300) INFO: decoder input length: 87
2022-12-06 16:44:58,486 (beam_search:1301) INFO: max output length: 11
2022-12-06 16:44:59,051 (beam_search:1380) INFO: adding <eos> in the last position in the loop
2022-12-06 16:44:59,053 (beam_search:1316) INFO: no hypothesis. Finish decoding.
2022-12-06 16:44:59,054 (beam_search:1337) INFO:  -0.00 * 0.5 =  -0.00 for ctc
2022-12-06 16:44:59,054 (beam_search:1340) INFO: total log probability: -1.09
2022-12-06 16:44:59,054 (beam_search:1341) INFO: normalized log probability: -0.08
2022-12-06 16:44:59,054 (beam_search:1342) INFO: total number of ended hypotheses: 10
2022-12-06 16:44:59,054 (beam_search:1344) INFO: best hypo: 目前矿山企业已基本关闭

2022-12-06 16:44:59,055 (asr_inference_paraformer:337) INFO: decoding, feature length: 354, forward_time: 18.9701, rtf: 5.3588
2022-12-06 16:44:59,095 (asr_inference_paraformer:359) INFO: decoding, predictions: 目前矿山企业已基本关闭
2022-12-06 16:44:59,104 (asr_inference_paraformer:324) INFO: decoding, utt_id: ['BAC009S0761W0470']
Traceback (most recent call last):
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/bin/asr_inference_launch.py", line 225, in <module>
    main()
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/bin/asr_inference_launch.py", line 219, in main
    inference(**kwargs)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/bin/asr_inference_paraformer.py", line 329, in inference
    results = speech2text(**batch)
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/bin/asr_inference_paraformer.py", line 193, in __call__
    decoder_outs = self.asr_model.cal_decoder_with_predictor(enc, enc_len, pre_acoustic_embeds, pre_token_length)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/models/e2e_asr_paraformer.py", line 333, in cal_decoder_with_predictor
    decoder_out, _ = self.decoder(
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/models/decoder/transformer_decoder.py", line 504, in forward
    x, tgt_mask, memory, memory_mask = decoder(
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/models/decoder/transformer_decoder.py", line 123, in forward
    x = residual + self.dropout(self.self_attn(tgt_q, tgt, tgt, tgt_q_mask))
  File "/home/environment/hwang/anaconda3/envs/oslasr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/modules/attention.py", line 114, in forward
    return self.forward_attention(v, scores, mask)
  File "/home/work_nfs4_ssd/hwang/workspaces/funasr/funasr/modules/attention.py", line 83, in forward_attention
    scores = scores.masked_fill(mask, min_value)
RuntimeError: The size of tensor a (13) must match the size of tensor b (14) at non-singleton dimension 3
\# Accounting: time=2679 threads=1
\# Ended (code 1) at Tue Dec  6 16:45:13 CST 2022, elapsed time 2679 seconds

May be, it is a coding bug?

**Comment by MrSupW** [comment]
![image](https://user-images.githubusercontent.com/57617568/205878561-7b7ef8ab-dfd3-48fd-9494-50dcf384b039.png)
Does this code change get blame for the error?

**Comment by MrSupW** [comment]
> ![image](https://user-images.githubusercontent.com/57617568/205878561-7b7ef8ab-dfd3-48fd-9494-50dcf384b039.png) Does this code change get blame for the error?

Yes, I retrieve this modification, and everything goes well.

**Comment by langgz** [comment]
what's the version of predictor in you model? the cif_predictor ? or cif_predictor_v2 ?

**Comment by MrSupW** [comment]
> what's the version of predictor in you model? the cif_predictor ? or cif_predictor_v2 ?
cif_predictor default configuration in aishell1 paraformer baseline

**Comment by langgz** [comment]
Thank you for your feedback! If the batchsize is 1, it is ok to retrieve above modification. We will update a new version tomorrow, which could decode with batch.
