### ISSUE TITLE
训练模型需要联网吗？

### ISSUE THREAD

**Issue by GlocKieHuan** [alibaba-damo-academy/FunASR#924]
指定了模型路径，仍然日志打印网络连接错误。
(funasr) ctc@HP-Z6-G4-Workstation:~/anaconda3/envs/funasr/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch$ python finetune.py 
2023-09-05 17:08:25,544 - modelscope - INFO - PyTorch version 1.13.1+cu117 Found.
2023-09-05 17:08:25,544 - modelscope - INFO - Loading ast index from /home/ctc/.cache/modelscope/ast_indexer
2023-09-05 17:08:25,607 - modelscope - INFO - Loading done! Current index file version is 1.7.1, with md5 de9309ed85e54c9a427056d24034fdcf and a total number of 861 components indexed
Traceback (most recent call last):
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 721, in urlopen
    chunked=chunked,
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fc2998f4610>, 'Connection to www.modelscope.cn timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in urlopen
    **response_kw
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in urlopen
    **response_kw
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/export (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc2998f4610>, 'Connection to www.modelscope.cn timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/modelscope/pipelines/util.py", line 35, in is_official_hub_impl
    _ = HubApi().get_model(path, revision=revision)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/modelscope/hub/api.py", line 226, in get_model
    r = self.session.get(path, cookies=cookies, headers=self.headers)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/export (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc2998f4610>, 'Connection to www.modelscope.cn timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "finetune.py", line 48, in <module>
    modelscope_finetune(params)
  File "finetune.py", line 24, in modelscope_finetune
    trainer = build_trainer(Trainers.speech_asr_trainer, default_args=kwargs)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/modelscope/trainers/builder.py", line 29, in build_trainer
    if is_official_hub_path(model, revision=model_revision):
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/modelscope/pipelines/util.py", line 41, in is_official_hub_path
    return is_official_hub_impl(path)
  File "/home/ctc/anaconda3/envs/funasr/lib/python3.7/site-packages/modelscope/pipelines/util.py", line 38, in is_official_hub_impl
    raise ValueError(f'invalid model repo path {e}')
ValueError: invalid model repo path HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/export (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc2998f4610>, 'Connection to www.modelscope.cn timed out. (connect timeout=60)'))
(funasr) ctc@HP-Z6-G4-Workstation:~/anaconda3/envs/funasr/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch$

**Comment by GlocKieHuan** [comment]
你好呀，这里是GH的邮件自动回复，你的邮件我已经收到啦，祝好~~~
